/-
  Test: Golden Value Validation

  Loads golden values generated by scripts/yolo_golden_gen.py and validates:
  1. Binary file loading works correctly
  2. Weight quantization sanity checks (INT4 range, bias non-zero)
  3. Activation data shape/range checks
  4. Dequantization of golden weights produces valid INT8 range
-/

import LSpec
import Tests.YOLOv8.GoldenLoader
import Examples.YOLOv8.Primitives.Dequant

open cktlean.Examples.YOLOv8.Tests.GoldenLoader
open cktlean.Examples.YOLOv8.Primitives.Dequant
open cktlean.Core.Domain
open cktlean.Core.Signal

namespace cktlean.Examples.YOLOv8.Tests.TestGoldenValues

def goldenDir : String := "Tests/yolo-golden"

/-- Check if golden values directory exists. -/
def checkGoldenDir : IO Bool := do
  System.FilePath.pathExists goldenDir

/-- Test: Load and validate layer 0 weights (INT4 packed). -/
def testLoadWeights : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let weights ← loadInt4Array s!"{goldenDir}/weights/layer_00_weights.bin"
  -- INT4 weights should be in range [-8, 7]
  let mut allInRange := true
  for i in [:weights.size] do
    let v := weights[i]!.toInt
    if v < -8 || v > 7 then
      allInRange := false
  return LSpec.test s!"layer_00 weights loaded ({weights.size} values)" (weights.size > 0) ++
    LSpec.test "layer_00 weights in INT4 range [-8,7]" allInRange

/-- Test: Load and validate layer 0 biases (INT32). -/
def testLoadBiases : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let biases ← loadInt32Array s!"{goldenDir}/weights/layer_00_bias.bin"
  return LSpec.test s!"layer_00 biases loaded ({biases.size} values)" (biases.size > 0)

/-- Test: Load and validate layer 0 activation output (INT8). -/
def testLoadActivations : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let acts ← loadInt8Array s!"{goldenDir}/activations/layer_00_output.bin"
  -- INT8 activations should be in range [-128, 127]
  let mut allInRange := true
  for i in [:acts.size] do
    let v := acts[i]!.toInt
    if v < -128 || v > 127 then
      allInRange := false
  return LSpec.test s!"layer_00 activations loaded ({acts.size} values)" (acts.size > 0) ++
    LSpec.test "layer_00 activations in INT8 range" allInRange

/-- Test: Load input image and check dimensions. -/
def testLoadInputImage : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let image ← loadInt8Array s!"{goldenDir}/input_image.bin"
  -- 160×160×3 = 76800 bytes
  return LSpec.test s!"input image loaded ({image.size} bytes)" (image.size == 76800)

/-- Test: Validate dequantization of golden INT4 weights.
    Load packed weights, unpack via dequant primitives, check sign extension. -/
def testDequantGolden : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let weights4 ← loadInt4Array s!"{goldenDir}/weights/layer_00_weights.bin"
  if weights4.size == 0 then
    return LSpec.test "weights not empty" false
  -- Pick first 10 weights and verify dequantization
  let numToTest := min 10 weights4.size
  let mut allCorrect := true
  for i in [:numToTest] do
    let w4 := weights4[i]!
    let sig4 : Signal defaultDomain (BitVec 4) := Signal.pure w4
    let sig8 := dequantInt4ToInt8 sig4
    let result := sig8.atTime 0
    -- Sign extension should preserve the signed value
    if result.toInt != w4.toInt then
      allCorrect := false
  return LSpec.test s!"dequant golden weights sign-extend correctly ({numToTest} tested)" allCorrect

/-- Test: Compute self-similarity of golden activations (should be 1.0). -/
def testSelfSimilarity : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let acts ← loadInt8Array s!"{goldenDir}/activations/layer_00_output.bin"
  if acts.size == 0 then
    return LSpec.test "activations not empty" false
  let cosSim := cosineSimilarityInt8 acts acts
  return LSpec.test s!"self-similarity = {cosSim} (should be 1.0)" (cosSim == 1.0)

/-- Test: Multiple layers have distinct weights. -/
def testLayerDiversity : IO LSpec.TestSeq := do
  let dirFound ← checkGoldenDir
  if !dirFound then
    return LSpec.test "golden dir exists (skipped)" true
  let w0 ← loadInt4Array s!"{goldenDir}/weights/layer_00_weights.bin"
  let w1 ← loadInt4Array s!"{goldenDir}/weights/layer_01_weights.bin"
  -- Different layers should have different weights
  let areDifferent := w0.size != w1.size || Id.run do
    let n := min w0.size w1.size
    let n' := min n 100
    let mut diffCount : Nat := 0
    for i in [:n'] do
      if w0[i]! != w1[i]! then
        diffCount := diffCount + 1
    return diffCount > 0
  return LSpec.test "layer 0 and layer 1 have different weights" areDifferent

def allTests : IO LSpec.TestSeq := do
  let t1 ← testLoadWeights
  let t2 ← testLoadBiases
  let t3 ← testLoadActivations
  let t4 ← testLoadInputImage
  let t5 ← testDequantGolden
  let t6 ← testSelfSimilarity
  let t7 ← testLayerDiversity
  return LSpec.group "Golden Value Validation" (
    LSpec.group "File Loading" (t1 ++ t2 ++ t3 ++ t4) ++
    LSpec.group "Dequantization" t5 ++
    LSpec.group "Metrics" (t6 ++ t7)
  )

end cktlean.Examples.YOLOv8.Tests.TestGoldenValues
