/-
  Production-entry smoke tests for the explicit, proof-carrying combinational
  compiler.  The ordinary Signal/MetaM frontend is intentionally absent.
-/

import Sparkle.Compiler.CombElab

namespace Tests.CombElabTests

open Sparkle.IR.AST
open Sparkle.IR.Type
open Sparkle.Compiler.CombCorrectness
open Sparkle.Compiler.CombElab

private def w : DimExpr := .param "W"

def passthroughDesign : CombDesign :=
  { name := "verified_passthrough"
    parameters := [{ name := "W", defaultValue := 8 }]
    inputs := [{ name := "input_data", width := w }]
    outputs :=
      [{ name := "output_data", width := w,
         rhs := .resize w (.ref "input_data") }] }

theorem passthroughDesign_supported : SupportedComb passthroughDesign := by
  simp [SupportedComb, configDomain, ParametersDeclared, dimensions,
    passthroughDesign, allBindings, BindingsScoped, CombExpr.refs,
    CombExpr.dimensions, dimParameters, w]

def certifiedPassthrough : CertifiedCombDesign :=
  { design := passthroughDesign
    supported := passthroughDesign_supported }

private def requireCheck (label : String) (condition : Bool) : IO Unit :=
  unless condition do
    throw <| IO.userError s!"verified combinational production entry failed: {label}"

def runTests : IO Unit := do
  let expected := compileSupportedComb certifiedPassthrough
  let checked ← match toCoreIRChecked certifiedPassthrough with
    | .ok module => pure module
    | .error message => throw <| IO.userError message
  requireCheck "checked API returns the exact theorem-covered Core IR"
    (checked == expected)
  let verilog ← match toVerilogChecked certifiedPassthrough with
    | .ok text => pure text
    | .error message => throw <| IO.userError message
  requireCheck "checked Verilog has the expected module"
    (verilog.startsWith "// Generated by Sparkle HDL\n// Module: verified_passthrough")
  requireCheck "checked Verilog is complete" (verilog.endsWith "endmodule\n")
  IO.println "Verified combinational production-entry API tests passed"

-- These exercise the declaration resolver and evaluator used by the isolated
-- commands in addition to the pure API checks above.
#synthesizeComb certifiedPassthrough
#synthesizeCombVerilog certifiedPassthrough

def ordinaryValue : Nat := 8

/--
error: 'Tests.CombElabTests.ordinaryValue' has type 'Nat', but the verified combinational path requires a closed Sparkle.Compiler.CombCorrectness.CertifiedCombDesign.
-/
#guard_msgs in
#synthesizeComb ordinaryValue

unsafe def substitutedNameImpl : String := "runtime_substitution"

@[implemented_by substitutedNameImpl]
def substitutedName : String := "kernel_name"

def substitutedDesign : CombDesign :=
  { passthroughDesign with name := substitutedName }

theorem substitutedDesign_supported : SupportedComb substitutedDesign := by
  simpa [substitutedDesign] using passthroughDesign_supported

def substitutedCertified : CertifiedCombDesign :=
  ⟨substitutedDesign, substitutedDesign_supported⟩

/--
error: Certified combinational design runtime closure reaches unproved @[implemented_by] definition 'Tests.CombElabTests.substitutedName'.
-/
#guard_msgs in
#synthesizeComb substitutedCertified

#eval runTests

end Tests.CombElabTests
