import Sparkle.Compiler.Elab
import Tests.SymbolicParameterCircuits

#synthesizeParameterizedVerilog symbolicIdentity [W := 8]
#synthesizeParameterizedVerilog symbolicXor [W := 8]
#synthesizeParameterizedVerilog symbolicConcat [HI := 5, LO := 3]
#synthesizeParameterizedVerilog symbolicSliceLow [W := 8]
#synthesizeParameterizedVerilog symbolicZeroExtend [W := 8]
#synthesizeParameterizedVerilog symbolicCastExtend [W := 8]
#synthesizeParameterizedVerilog symbolicCastTrunc [W := 8]
#synthesizeParameterizedVerilog symbolicModulo [W := 8]
#synthesizeParameterizedVerilog symbolicRepeatVector [W := 3, N := 4]
#synthesizeParameterizedVerilog symbolicIotaVector1 [W := 4, N := 3]
#synthesizeParameterizedVerilogDesign symbolicMapChunks [W := 3, N := 4]
#synthesizeParameterizedVerilogDesign symbolicMapChunksNarrow [N := 3]
#synthesizeParameterizedVerilogDesign symbolicMapChunksWithIndex [W := 3, N := 4]
#synthesizeParameterizedVerilog symbolicRegister [W := 8]
#synthesizeParameterizedVerilog symbolicMemory [ADDR_W := 3, DATA_W := 8]
#synthesizeParameterizedVerilog symbolicComboMemory [ADDR_W := 3, DATA_W := 8]
#synthesizeParameterizedVerilogDesign symbolicXorHierarchy [W := 8]
#synthesizeParameterizedVerilog symbolicLoopXor [W := 8]
#synthesizeParameterizedVerilog symbolicDerivedLoop [DEPTH := 8]
#synthesizeParameterizedVerilog symbolicDerivedAlias [DEPTH := 8]
#synthesizeParameterizedVerilog symbolicLoopBundle [W := 8]
#synthesizeParameterizedVerilog symbolicPairLoop [W := 8]
#synthesizeParameterizedVerilog symbolicWideTupleLoop [W := 3]
#synthesizeParameterizedVerilog symbolicDepthCompare [DEPTH := 8]
#synthesizeParameterizedVerilog symbolicGenerateNot [W := 8]
#synthesizeParameterizedVerilog symbolicLetMaskXor [W := 8]
#synthesizeParameterizedVerilog symbolicParameterLiteral [D := 6]
#synthesizeParameterizedVerilog symbolicValueExpression [W := 3]
#synthesizeParameterizedVerilog symbolicBundleAllOutput [W := 3]
#synthesizeParameterizedVerilog symbolicPopCount [W := 3]
#synthesizeParameterizedVerilog symbolicUnsignedGE [W := 3]
#synthesizeParameterizedVerilog symbolicReverseBits [W := 3]
#synthesizeParameterizedVerilog symbolicReverseBlocks [W := 16, BLOCKS := 2]
