from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "agent"))

import evaluator as evaluator_module  # noqa: E402
from evaluator import Evaluator  # noqa: E402
from lean_repl import _parse_raw  # noqa: E402


CHILD = """// Generated by Sparkle HDL
// Module: child

module child #(parameter W = 8) (
    input logic [W-1:0] x,
    output logic [W-1:0] y
);
    assign y = x;
endmodule"""

PARENT = """// Generated by Sparkle HDL
// Module: parent

module parent #(parameter W = 8) (
    input logic [W-1:0] x,
    output logic [W-1:0] y
);
    child #(.W(W)) u_child (.x(x), .y(y));
endmodule"""


def _build_output(*modules: str) -> str:
    return "\n\n".join(modules) + "\n\n-- Hierarchical Verilog successfully generated!\n"


def test_extract_sv_keeps_every_module_from_the_last_synthesis_command():
    stale = """// Generated by Sparkle HDL
// Module: stale
module stale(output logic y);
    assign y = 1'b0;
endmodule"""
    output = (
        _build_output(stale)
        + "unrelated lake output\n"
        + _build_output(CHILD, PARENT)
        + "trailing non-Verilog diagnostic\n"
    )

    extracted = Evaluator._extract_sv(output)

    assert "module stale" not in extracted
    assert "module child" in extracted
    assert "module parent" in extracted
    assert extracted.count("endmodule") == 2
    assert "successfully generated" not in extracted
    assert "trailing non-Verilog" not in extracted


def test_generated_top_prefers_benchmark_name_then_falls_back_to_last_module():
    reverse_order = f"{PARENT}\n\n{CHILD}"

    preferred_name, preferred_ports = Evaluator._generated_top_module_ports(
        reverse_order, "parent"
    )
    fallback_name, fallback_ports = Evaluator._generated_top_module_ports(
        reverse_order
    )

    assert preferred_name == "parent"
    assert [name for _, _, name in preferred_ports] == ["x", "y"]
    assert fallback_name == "child"
    assert [name for _, _, name in fallback_ports] == ["x", "y"]


@pytest.mark.skipif(
    shutil.which("iverilog") is None or shutil.which("vvp") is None,
    reason="iverilog is required for hierarchical extraction integration test",
)
def test_extracted_hierarchical_design_elaborates_and_simulates(tmp_path: Path):
    extracted = Evaluator._extract_sv(_build_output(CHILD, PARENT))
    testbench = """
module tb;
    logic [2:0] x;
    logic [2:0] y;
    parent #(.W(3)) dut (.x(x), .y(y));
    initial begin
        x = 3'b101;
        #1;
        if (y !== x) $fatal(1, "hierarchical output mismatch");
        $display("PASS hierarchical evaluator extraction");
        $finish;
    end
endmodule
"""
    source = tmp_path / "hierarchical.sv"
    image = tmp_path / "hierarchical.vvp"
    source.write_text(f"{extracted}\n\n{testbench}")

    compile_result = subprocess.run(
        ["iverilog", "-g2012", "-s", "tb", "-o", str(image), str(source)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert compile_result.returncode == 0, (
        compile_result.stdout + compile_result.stderr
    )
    simulation = subprocess.run(
        ["vvp", str(image)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert simulation.returncode == 0, simulation.stdout + simulation.stderr
    assert "PASS hierarchical evaluator extraction" in simulation.stdout


def test_evaluate_preserves_child_and_top_for_lint_simulation_and_synthesis(
    tmp_path: Path,
    monkeypatch,
):
    problem_id = "hierarchical_native"
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / f"{problem_id}.lean").write_text("-- compile is stubbed\n")
    build_output = _build_output(CHILD, PARENT)

    monkeypatch.setattr(
        evaluator_module.subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(
            returncode=0,
            stdout=build_output,
            stderr="",
        ),
    )

    class DatasetStub:
        @staticmethod
        def load_problem(_prob_id: str):
            return SimpleNamespace(design_name="parent")

    class RecordingEvaluator(Evaluator):
        def __init__(self):
            super().__init__(
                project_root=tmp_path,
                dataset="verilogeval",
                dataset_obj=DatasetStub(),
                enable_synth=True,
            )
            self.seen: list[tuple[str, str]] = []

        def _run_lint(self, sv_file: Path) -> bool:
            code = sv_file.read_text()
            self.seen.append(("lint", code))
            return "module child" in code and "module parent" in code

        def _run_sim(
            self,
            _prob_id: str,
            sv_code: str,
            sparkle_mod_name: str,
            sparkle_ports,
            _run_dir: Path,
        ):
            self.seen.append(("sim", sv_code))
            assert sparkle_mod_name == "parent"
            assert [name for _, _, name in sparkle_ports] == ["x", "y"]
            assert "module child" in sv_code and "module parent" in sv_code
            return "sim_pass", 0, "hierarchical simulation passed"

        def _run_synthesis(
            self,
            _prob_id: str,
            sv_code: str,
            top_module: str,
            _run_dir: Path,
        ) -> dict:
            self.seen.append(("synth", sv_code))
            assert top_module == "parent"
            assert "module child" in sv_code and "module parent" in sv_code
            return {"synth_pass": True}

    evaluator = RecordingEvaluator()
    result = evaluator.evaluate(problem_id, tmp_path / "run")

    assert result["compile_pass"] is True
    assert result["sv_extracted"] is True
    assert result["lint_pass"] is True
    assert result["sim_status"] == "sim_pass"
    assert result["synth_pass"] is True
    assert [stage for stage, _ in evaluator.seen] == ["lint", "sim", "synth"]
    saved_sv = (tmp_path / "run" / "sv" / f"{problem_id}.sv").read_text()
    assert "module child" in saved_sv and "module parent" in saved_sv


def test_repl_parser_combines_hierarchical_verilog_info_records():
    result = _parse_raw(
        {
            "messages": [
                {"severity": "info", "data": CHILD},
                {"severity": "info", "data": PARENT},
            ],
            "sorries": [],
            "tactics": [],
            "env": 3,
        },
        elapsed=0.1,
    )

    assert result.passed is True
    assert result.verilog is not None
    assert "module child" in result.verilog
    assert "module parent" in result.verilog
