from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "agent"))

from cvdp_specialization import (  # noqa: E402
    FiniteParameterPlan,
    SpecializationCase,
    discover_finite_parameter_plan,
    specialization_module_name,
)
from dataset import Dataset  # noqa: E402
from evaluator import (  # noqa: E402
    Evaluator,
    _safe_sv_int_expr,
    _specialize_sv_type,
    generate_cvdp_specialization_wrapper,
)
from lean_repl import _parse_raw  # noqa: E402
from search import (  # noqa: E402
    _p0_benchmark_expected_ports,
    _p0_parse_parameters_from_prompt,
)


P0_PARAMETER_TASKS = {
    "cvdp_copilot_axil_precision_counter_0001": 9,
    "cvdp_copilot_car_parking_management_0001": 3,
    "cvdp_copilot_digital_dice_roller_0004": 4,
    "cvdp_copilot_filo_0005": 5,
    "cvdp_copilot_gf_multiplier_0021": 4,
    "cvdp_copilot_hamming_code_tx_and_rx_0009": 6,
    "cvdp_copilot_hamming_code_tx_and_rx_0011": 6,
    "cvdp_copilot_nbit_swizzling_0001": 5,
    "cvdp_copilot_restoring_division_0001": 5,
    "cvdp_copilot_square_root_0003": 4,
    "cvdp_copilot_sync_lifo_0001": 5,
    "cvdp_copilot_word_reducer_0008": 4,
}


def _width_plan(
    widths: tuple[int, ...] = (3, 5),
    *,
    design_name: str = "p0_xor",
    parameter_name: str = "WIDTH",
) -> FiniteParameterPlan:
    return FiniteParameterPlan(
        design_name=design_name,
        parameter_names=(parameter_name,),
        cases=tuple(
            SpecializationCase(
                ((parameter_name, width),),
                f"{design_name}__p0__{parameter_name}_{width}",
            )
            for width in widths
        ),
    )


def test_specialization_module_name_keeps_numeric_value_suffix_readable():
    assert specialization_module_name("dut", {"WIDTH": 3}, ("WIDTH",)) == (
        "dut__p0__WIDTH_3"
    )
    assert specialization_module_name("dut", {"OFFSET": -2}, ("OFFSET",)) == (
        "dut__p0__OFFSET_neg_2"
    )


def _xor_modules(plan: FiniteParameterPlan) -> dict[str, str]:
    modules = {}
    for case in plan.cases:
        width = next(iter(case.values.values()))
        modules[case.module_name] = f"""
        // Generated by Sparkle HDL
        module {case.module_name} (
            input logic [{width - 1}:0] _gen_lhs,
            input logic [{width - 1}:0] _gen_rhs,
            output logic [{width - 1}:0] out
        );
            assign out = _gen_lhs ^ _gen_rhs;
        endmodule
        """
    return modules


def _generate_xor_wrapper(
    plan: FiniteParameterPlan,
    modules: dict[str, str] | None = None,
):
    return generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules=modules if modules is not None else _xor_modules(plan),
        expected_ports=[
            ("input", "logic [WIDTH-1:0]", "lhs"),
            ("input", "logic [WIDTH-1:0]", "rhs"),
            ("output", "logic [WIDTH-1:0]", "out"),
        ],
        ref_code="",
        harness_files={
            "src/test_runner.py": (
                "runner.build(parameters={'WIDTH': WIDTH})\n"
                "dut.lhs.value = 0\ndut.rhs.value = 0\nint(dut.out.value)"
            )
        },
    )


def test_real_cvdp_p0_family_is_12_tasks_and_60_specializations():
    dataset = Dataset("cvdp", PROJECT_ROOT)
    try:
        dataset.discover_problems(limit=1)
    except FileNotFoundError as exc:
        pytest.skip(str(exc))

    plans = {}
    for prob_id, expected_count in P0_PARAMETER_TASKS.items():
        info = dataset.load_problem(prob_id)
        plan = discover_finite_parameter_plan(
            design_name=info.design_name,
            harness_files=info.metadata["harness_files"],
        )
        assert plan.supported, (prob_id, plan.diagnostics)
        assert len(plan.cases) == expected_count, prob_id
        plans[prob_id] = plan

    assert sum(len(plan.cases) for plan in plans.values()) == 60

    assert [
        case.values for case in plans["cvdp_copilot_filo_0005"].cases
    ] == [
        {"DATA_WIDTH": 8, "FILO_DEPTH": 8},
        {"DATA_WIDTH": 10, "FILO_DEPTH": 12},
        {"DATA_WIDTH": 10, "FILO_DEPTH": 16},
        {"DATA_WIDTH": 12, "FILO_DEPTH": 12},
        {"DATA_WIDTH": 12, "FILO_DEPTH": 16},
    ]

    expected_hamming = [
        {"DATA_WIDTH": 4, "PARITY_BIT": 3},
        {"DATA_WIDTH": 8, "PARITY_BIT": 4},
        {"DATA_WIDTH": 16, "PARITY_BIT": 5},
        {"DATA_WIDTH": 32, "PARITY_BIT": 6},
        {"DATA_WIDTH": 64, "PARITY_BIT": 7},
        {"DATA_WIDTH": 128, "PARITY_BIT": 8},
    ]
    for prob_id in (
        "cvdp_copilot_hamming_code_tx_and_rx_0009",
        "cvdp_copilot_hamming_code_tx_and_rx_0011",
    ):
        assert [case.values for case in plans[prob_id].cases] == expected_hamming

    assert [
        case.values for case in plans["cvdp_copilot_sync_lifo_0001"].cases
    ] == [
        {"ADDR_WIDTH": 2, "DATA_WIDTH": 4},
        {"ADDR_WIDTH": 3, "DATA_WIDTH": 8},
        {"ADDR_WIDTH": 4, "DATA_WIDTH": 16},
        {"ADDR_WIDTH": 6, "DATA_WIDTH": 64},
        {"ADDR_WIDTH": 7, "DATA_WIDTH": 128},
    ]


def test_dice_contract_recovers_symbolic_output_and_derived_width():
    dataset = Dataset("cvdp", PROJECT_ROOT)
    try:
        info = dataset.load_problem("cvdp_copilot_digital_dice_roller_0004")
    except FileNotFoundError as exc:
        pytest.skip(str(exc))
    plan = discover_finite_parameter_plan(
        design_name=info.design_name,
        harness_files=info.metadata["harness_files"],
    )
    payload = plan.to_dict()
    info.metadata["finite_parameter_plan"] = payload

    ports = _p0_benchmark_expected_ports(info)
    prompt_parameters = _p0_parse_parameters_from_prompt(info.prompt_text)
    public_types = "\n".join(typ for _, typ, _ in ports)
    derived = {
        name
        for name in prompt_parameters - set(plan.parameter_names)
        if re.search(rf"\b{re.escape(name)}\b", public_types)
    }

    assert (
        "output",
        "logic [(NUM_DICE * BIT_WIDTH) - 1:0]",
        "dice_values",
    ) in ports
    assert derived == {"BIT_WIDTH"}


def test_default_collected_pytest_build_is_part_of_parameter_family():
    plan = discover_finite_parameter_plan(
        design_name="fifo",
        harness_files={
            "src/test_runner.py": """
                import pytest

                def test_runner(DATA_WIDTH=8, DEPTH=8):
                    runner.build(parameters={
                        "DATA_WIDTH": DATA_WIDTH,
                        "DEPTH": DEPTH,
                    })

                @pytest.mark.parametrize("DATA_WIDTH", [10, 12])
                @pytest.mark.parametrize("DEPTH", [12, 16])
                def test_sweep(DATA_WIDTH, DEPTH):
                    test_runner(DATA_WIDTH=DATA_WIDTH, DEPTH=DEPTH)
            """
        },
    )

    assert [case.values for case in plan.cases] == [
        {"DATA_WIDTH": 8, "DEPTH": 8},
        {"DATA_WIDTH": 10, "DEPTH": 12},
        {"DATA_WIDTH": 10, "DEPTH": 16},
        {"DATA_WIDTH": 12, "DEPTH": 12},
        {"DATA_WIDTH": 12, "DEPTH": 16},
    ]


@pytest.mark.parametrize(
    "prob_id, scalar_ports",
    [
        (
            "cvdp_copilot_axil_precision_counter_0001",
            {"axi_aclk", "axi_aresetn", "axi_arready", "axi_awvalid", "axi_bready"},
        ),
        ("cvdp_copilot_restoring_division_0001", {"clk", "rst", "start", "valid"}),
        ("cvdp_copilot_square_root_0003", {"clk", "rst", "start", "done"}),
    ],
)
def test_p0_nearby_symbolic_width_does_not_pollute_scalar_ports(
    prob_id: str,
    scalar_ports: set[str],
):
    dataset = Dataset("cvdp", PROJECT_ROOT)
    try:
        info = dataset.load_problem(prob_id)
    except FileNotFoundError as exc:
        pytest.skip(str(exc))
    plan = discover_finite_parameter_plan(
        design_name=info.design_name,
        harness_files=info.metadata["harness_files"],
    )
    info.metadata["finite_parameter_plan"] = plan.to_dict()

    by_name = {name: typ for _, typ, name in _p0_benchmark_expected_ports(info)}

    assert {name: by_name[name] for name in scalar_ports} == {
        name: "logic" for name in scalar_ports
    }


def test_repl_preserves_every_generated_verilog_module():
    raw = {
        "env": 7,
        "messages": [
            {
                "severity": "info",
                "data": "// Generated by Sparkle HDL\nmodule p0_w3; endmodule",
            },
            {
                "severity": "info",
                "data": "// Generated by Sparkle HDL\nmodule p0_w5; endmodule",
            },
        ],
    }

    result = _parse_raw(raw, 0.25)

    assert result.passed and result.complete
    assert len(result.verilog_modules) == 2
    assert "module p0_w3" in result.verilog
    assert "module p0_w5" in result.verilog_modules[1]


def test_selector_requires_every_concrete_module():
    plan = _width_plan()
    modules = _xor_modules(plan)
    modules.pop(plan.cases[-1].module_name)

    code, manifest = _generate_xor_wrapper(plan, modules)

    assert code is None
    assert manifest["missing_modules"] == [plan.cases[-1].module_name]
    assert "missing concrete Sparkle modules" in manifest["error"]


def test_selector_covers_two_widths_and_rejects_unsupported_values():
    plan = _width_plan()

    code, manifest = _generate_xor_wrapper(plan)

    assert code is not None, manifest
    assert manifest["selector_generated"] is True
    assert "if ((WIDTH == 3))" in code
    assert "else if ((WIDTH == 5))" in code
    assert "p0_unsupported_parameter_combination" in code
    assert 'initial $error("Unsupported finite Sparkle parameter combination")' in code
    assert "assign lhs = '0" not in code
    assert "assign rhs = '0" not in code
    assert "CVDP adapter fallback" not in code


def test_derived_width_is_body_localparam_and_matches_concrete_cores():
    plan = _width_plan(
        (3, 5),
        design_name="Bit_Difference_Counter",
        parameter_name="BIT_WIDTH",
    )
    modules = {}
    for case, count_width in zip(plan.cases, (2, 3)):
        bit_width = case.values["BIT_WIDTH"]
        modules[case.module_name] = f"""
        module {case.module_name} (
            input logic [{bit_width - 1}:0] _gen_input_A,
            input logic [{bit_width - 1}:0] _gen_input_B,
            output logic [{count_width - 1}:0] count
        );
            assign count = '0;
        endmodule
        """

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules=modules,
        expected_ports=[
            ("input", "logic [BIT_WIDTH-1:0]", "input_A"),
            ("input", "logic [BIT_WIDTH-1:0]", "input_B"),
            ("output", "logic [COUNT_WIDTH-1:0]", "count"),
        ],
        ref_code="",
        harness_files={
            "src/test.py": (
                "runner.build(parameters={'BIT_WIDTH': BIT_WIDTH})\n"
                "dut.input_A.value = 0\ndut.input_B.value = 0\n"
                "int(dut.count.value)\nint(dut.COUNT_WIDTH.value)"
            )
        },
        derived_parameter_names={"COUNT_WIDTH"},
    )

    assert code is not None, manifest
    parameter_header = code.split(")\n (", 1)[0]
    assert "parameter integer BIT_WIDTH" in parameter_header
    assert "parameter integer COUNT_WIDTH" not in parameter_header
    assert "localparam integer COUNT_WIDTH" in code
    assert manifest["derived_parameter_values"] == {"COUNT_WIDTH": [2, 3]}


def test_derived_public_value_conflicting_with_core_width_is_rejected():
    plan = _width_plan(
        (3,),
        design_name="Bit_Difference_Counter",
        parameter_name="BIT_WIDTH",
    )
    case = plan.cases[0]
    modules = {
        case.module_name: f"""
        module {case.module_name} (
            input logic [2:0] _gen_input_A,
            output logic [2:0] count
        );
            assign count = '0;
        endmodule
        """
    }

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules=modules,
        expected_ports=[
            ("input", "logic [BIT_WIDTH-1:0]", "input_A"),
            ("output", "logic [COUNT_WIDTH-1:0]", "count"),
        ],
        ref_code="",
        harness_files={"src/test.py": "dut.input_A.value = 0\nint(dut.count.value)"},
        derived_parameter_names={"COUNT_WIDTH"},
    )

    assert code is None
    assert "conflicts with concrete module width inference" in manifest["error"]


@pytest.mark.parametrize(
    "module_body, expected_ports",
    [
        (
            """
            module strict_core(
                input logic _gen_a,
                input logic _gen_hidden,
                output logic out
            ); assign out = _gen_a; endmodule
            """,
            [("input", "logic", "a"), ("output", "logic", "out")],
        ),
        (
            """
            module strict_core(
                input logic _gen_a,
                output logic out
            ); assign out = _gen_a; endmodule
            """,
            [
                ("input", "logic", "a"),
                ("input", "logic", "b"),
                ("output", "logic", "out"),
            ],
        ),
        (
            """
            module strict_core(
                input logic _gen_a,
                output logic left
            ); assign left = _gen_a; endmodule
            """,
            [
                ("input", "logic", "a"),
                ("output", "logic", "left"),
                ("output", "logic", "right"),
            ],
        ),
    ],
)
def test_p0_strict_adapter_rejects_incomplete_port_mapping(
    module_body: str,
    expected_ports: list[tuple[str, str, str]],
):
    plan = FiniteParameterPlan(
        design_name="strict_top",
        parameter_names=("WIDTH",),
        cases=(SpecializationCase((("WIDTH", 1),), "strict_core"),),
    )

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules={"strict_core": module_body},
        expected_ports=expected_ports,
        ref_code="",
        harness_files={"src/test.py": ""},
    )

    assert code is None
    assert "could not adapt concrete module strict_core" in manifest["error"]


def test_active_low_reset_bridges_domain_and_explicit_reset_separately():
    plan = FiniteParameterPlan(
        design_name="counter",
        parameter_names=("WIDTH",),
        cases=(SpecializationCase((("WIDTH", 8),), "counter_w8"),),
    )
    module = """
    module counter_w8(
        input logic clk,
        input logic rst,
        input logic _gen_reset,
        input logic [7:0] _gen_data,
        output logic [7:0] out
    );
        assign out = _gen_data;
    endmodule
    """

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules={"counter_w8": module},
        expected_ports=[
            ("input", "logic", "clock"),
            ("input", "logic", "reset"),
            ("input", "logic [WIDTH-1:0]", "data"),
            ("output", "logic [WIDTH-1:0]", "out"),
        ],
        ref_code="",
        harness_files={"src/test.py": ""},
        reset_polarities={"reset": "active-low"},
    )

    assert code is not None, manifest
    adapter_match = re.search(
        r"module counter_w8__cvdp_adapter.*?endmodule", code, re.DOTALL
    )
    assert adapter_match
    adapter = adapter_match.group(0)
    assert ".clk(clock)" in adapter
    assert ".rst(~reset)" in adapter
    assert "._gen_reset(reset)" in adapter


def test_named_active_low_reset_alias_bridges_domain_and_explicit_reset():
    plan = FiniteParameterPlan(
        design_name="lifo",
        parameter_names=("WIDTH",),
        cases=(SpecializationCase((("WIDTH", 8),), "lifo_w8"),),
    )
    module = """
    module lifo_w8(
        input logic clk,
        input logic rst,
        input logic _gen_rstN,
        input logic [7:0] _gen_data,
        output logic [7:0] out
    );
        assign out = _gen_data;
    endmodule
    """

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules={"lifo_w8": module},
        expected_ports=[
            ("input", "logic", "clock"),
            ("input", "logic", "reset"),
            ("input", "logic [WIDTH-1:0]", "data"),
            ("output", "logic [WIDTH-1:0]", "out"),
        ],
        ref_code="",
        harness_files={"src/test.py": ""},
        reset_polarities={"reset": "active-low"},
    )

    assert code is not None, manifest
    adapter_match = re.search(
        r"module lifo_w8__cvdp_adapter.*?endmodule", code, re.DOTALL
    )
    assert adapter_match
    adapter = adapter_match.group(0)
    assert ".clk(clock)" in adapter
    assert ".rst(~reset)" in adapter
    assert "._gen_rstN(reset)" in adapter


def test_strict_adapter_maps_one_equal_width_concat_output_directly():
    plan = FiniteParameterPlan(
        design_name="encoder",
        parameter_names=("WIDTH",),
        cases=(SpecializationCase((("WIDTH", 4),), "encoder_w4"),),
    )
    module = """
    module encoder_w4(
        input logic [3:0] _gen_data_in,
        output logic [4:0] out
    );
        assign out = {_gen_data_in, 1'b0};
    endmodule
    """

    code, manifest = generate_cvdp_specialization_wrapper(
        design_name=plan.design_name,
        plan=plan,
        modules={"encoder_w4": module},
        expected_ports=[
            ("input", "logic [WIDTH-1:0]", "data_in"),
            ("output", "logic [WIDTH:0]", "data_out"),
        ],
        ref_code="",
        harness_files={"src/test.py": ""},
    )

    assert code is not None, manifest
    adapter_match = re.search(
        r"module encoder_w4__cvdp_adapter.*?endmodule", code, re.DOTALL
    )
    assert adapter_match
    assert "assign data_out = out_wire;" in adapter_match.group(0)


def test_symbolic_clog2_specialization_is_idempotent_and_evaluable():
    specialized = _specialize_sv_type(
        "logic [$clog2(BIT_WIDTH+1)-1:0]", {"BIT_WIDTH": 20}
    )

    assert "$$clog2" not in specialized
    assert specialized == "logic [$clog2(20+1)-1:0]"
    assert _safe_sv_int_expr("$clog2(20+1)-1") == 4


def test_lint_uses_configured_sim_image_when_host_iverilog_is_missing(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    sv_file = tmp_path / "dut.sv"
    sv_file.write_text("module dut; endmodule")
    captured = {}

    def fake_which(name: str):
        return "/usr/bin/docker" if name == "docker" else None

    def fake_run(command, **kwargs):
        captured["command"] = command
        return SimpleNamespace(returncode=0, stderr="")

    monkeypatch.setenv("OSS_SIM_IMAGE", "cvdp-agentic-eval:cocotb-2.0.1")
    monkeypatch.setattr("evaluator.shutil.which", fake_which)
    monkeypatch.setattr("evaluator.subprocess.run", fake_run)

    assert Evaluator._run_lint(sv_file)
    assert captured["command"][:6] == [
        "docker",
        "run",
        "--rm",
        "--entrypoint",
        "iverilog",
        "-v",
    ]
    assert "cvdp-agentic-eval:cocotb-2.0.1" in captured["command"]


def test_cvdp_compose_honors_configured_sim_image(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    info = SimpleNamespace(
        design_name="dut",
        ref_code="module dut(output logic out); endmodule",
        metadata={
            "harness_files": {
                "docker-compose.yml": (
                    "services:\n  direct:\n"
                    "    image: nvidia/cvdp-sim:v1.0.0\n"
                ),
                "src/.env": "TOPLEVEL=dut\nVERILOG_SOURCES=/code/rtl/dut.sv\n",
                "src/test_runner.py": "pass\n",
            },
            "verilog_sources": ["/code/rtl/dut.sv"],
        },
    )

    class DatasetStub:
        def load_problem(self, prob_id: str):
            return info

    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=DatasetStub(),
    )
    captured = {}

    def fake_local(sim_dir: Path):
        captured["compose"] = (sim_dir / "docker-compose.yml").read_text()
        return "sim_pass", 0, "ok"

    monkeypatch.setenv("OSS_SIM_IMAGE", "cvdp-agentic-eval:cocotb-2.0.1")
    monkeypatch.setenv("CVDP_SIM_MODE", "local")
    monkeypatch.setattr(evaluator, "_run_sim_cvdp_local", fake_local)

    status, mismatches, detail = evaluator._run_sim_cvdp(
        "p0_test",
        "module dut(output logic out); assign out = 1'b0; endmodule",
        "dut",
        [("output", "logic", "out")],
        tmp_path,
        direct_top=True,
        problem_info=info,
    )

    assert (status, mismatches, detail) == ("sim_pass", 0, "ok")
    assert "image: cvdp-agentic-eval:cocotb-2.0.1" in captured["compose"]
    assert "nvidia/cvdp-sim" not in captured["compose"]


def test_cvdp_docker_staging_mounts_generated_rtl(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    info = SimpleNamespace(
        design_name="dut",
        ref_code="module dut(output logic out); endmodule",
        metadata={
            "harness_files": {
                "docker-compose.yml": (
                    "services:\n  direct:\n    image: test-image\n"
                    "    volumes:\n      - ./src/:/src/:ro\n"
                ),
                "src/.env": "TOPLEVEL=dut\nVERILOG_SOURCES=/code/rtl/dut.sv\n",
                "src/test_runner.py": "pass\n",
            },
            "verilog_sources": ["/code/rtl/dut.sv"],
        },
    )

    class DatasetStub:
        def load_problem(self, prob_id: str):
            return info

    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=DatasetStub(),
    )
    captured = {}

    def fake_run(command, **kwargs):
        if command[:3] == ["docker", "compose", "version"]:
            return SimpleNamespace(returncode=0, stdout="", stderr="")
        if "up" in command:
            captured["compose"] = (
                Path(kwargs["cwd"]) / "docker-compose.yml"
            ).read_text()
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setenv("CVDP_SIM_MODE", "docker")
    monkeypatch.setattr("evaluator.subprocess.run", fake_run)

    status, mismatches, detail = evaluator._run_sim_cvdp(
        "p0_test",
        "module dut(output logic out); assign out = 1'b0; endmodule",
        "dut",
        [("output", "logic", "out")],
        tmp_path,
        direct_top=True,
        problem_info=info,
    )

    assert (status, mismatches, detail) == ("sim_pass", 0, "CVDP harness passed")
    assert "- ./rtl/:/code/rtl/:ro" in captured["compose"]


def test_cvdp_docker_timeout_always_cleans_up(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    info = SimpleNamespace(
        design_name="dut",
        ref_code="module dut(output logic out); endmodule",
        metadata={
            "harness_files": {
                "docker-compose.yml": (
                    "services:\n  direct:\n    image: test-image\n"
                    "    volumes:\n      - ./src/:/src/:ro\n"
                ),
                "src/.env": "TOPLEVEL=dut\nVERILOG_SOURCES=/code/rtl/dut.sv\n",
                "src/test_runner.py": "pass\n",
            },
            "verilog_sources": ["/code/rtl/dut.sv"],
        },
    )

    class DatasetStub:
        def load_problem(self, prob_id: str):
            return info

    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=DatasetStub(),
    )
    commands = []

    def fake_run(command, **kwargs):
        commands.append(command)
        if command[:3] == ["docker", "compose", "version"]:
            return SimpleNamespace(returncode=0, stdout="", stderr="")
        if "up" in command:
            raise subprocess.TimeoutExpired(command, kwargs.get("timeout", 0))
        return SimpleNamespace(returncode=0, stdout="removed\n", stderr="")

    monkeypatch.setenv("CVDP_SIM_MODE", "docker")
    monkeypatch.setattr("evaluator.subprocess.run", fake_run)

    status, mismatches, detail = evaluator._run_sim_cvdp(
        "p0_timeout",
        "module dut(output logic out); assign out = 1'b0; endmodule",
        "dut",
        [("output", "logic", "out")],
        tmp_path,
        direct_top=True,
        problem_info=info,
    )

    assert (status, mismatches, detail) == (
        "sim_error", -1, "CVDP docker simulation timeout"
    )
    assert any(
        "down" in command and "--remove-orphans" in command
        for command in commands
    )


def test_required_module_harness_does_not_save_partial_family(tmp_path: Path):
    from cktarchon.harness import AnthropicHarnessRunner

    runner = object.__new__(AnthropicHarnessRunner)
    runner.required_verilog_modules = ("p0_w3", "p0_w5")
    runner._last_complete_code = ""
    runner._last_complete_sequence = -1
    runner._tool_sequence = 4
    runner._autosave_last_complete_candidate = lambda: pytest.fail(
        "partial specialization family must not be autosaved"
    )
    result = SimpleNamespace(
        passed=True,
        complete=True,
        verilog="module p0_w3; endmodule",
        verilog_modules=["module p0_w3; endmodule"],
    )

    runner._remember_complete_candidate(
        "def p0_w3 := 1\n#synthesizeVerilog p0_w3", result
    )

    assert runner._last_complete_code == ""
    formatted = runner._format_lean_result(result)
    assert "P0 specialization modules: 1/2 present" in formatted
    assert "Missing required modules: p0_w5" in formatted
