import os
from pathlib import Path
import shutil
import subprocess

import pytest

ROOT = Path(__file__).resolve().parents[1]
LAKE = os.environ.get("LAKE_PATH", str(Path.home() / ".elan/bin/lake"))


def generate(tmp_path, lean):
    if not Path(LAKE).exists() or not shutil.which("iverilog"):
        pytest.skip("built Sparkle, lake, and iverilog are required")
    source = tmp_path / "Export.lean"
    source.write_text(lean)
    result = subprocess.run([LAKE, "env", "lean", str(source)], cwd=ROOT,
                            capture_output=True, text=True, timeout=180)
    assert result.returncode == 0, result.stdout + result.stderr
    return result.stdout[result.stdout.index("// Generated by Sparkle HDL"):
                         result.stdout.rindex("endmodule") + len("endmodule")]


def compile_sv(tmp_path, sv, top, params=()):
    source = tmp_path / "export.sv"
    source.write_text(sv)
    result = subprocess.run(["iverilog", "-g2012", "-s", top,
                             *[f"-P{top}.{name}={value}" for name, value in params],
                             "-o", str(tmp_path / "export.vvp"), str(source)],
                            capture_output=True, text=True, timeout=20)
    assert result.returncode == 0, result.stderr


def test_one_bit_vector_remains_selectable_and_bool_remains_scalar(tmp_path):
    sv = generate(tmp_path, '''import cktlean.Backend.Verilog
open cktlean.IR.AST cktlean.Backend.Verilog
def testModule : Module := {
  name := "one_bit_vector"
  inputs := [{name := "a", ty := .bitVector 1}, {name := "flag", ty := .bit}]
  outputs := [{name := "b", ty := .bitVector 1}, {name := "c", ty := .bit}]
  wires := []
  body := [.assign "b" (.slice (.ref "a") 0 0), .assign "c" (.ref "flag")]
}
#eval IO.println (toVerilog testModule)
''')
    compile_sv(tmp_path, sv, "one_bit_vector")
    assert "input logic [0:0] a" in sv
    assert "input logic flag" in sv


HIERARCHY = '''import cktlean
import cktlean.Compiler.Elab
open cktlean.Core.Domain cktlean.Core.Signal
@[sparkle_module]
def exportLeaf {dom : DomainConfig} {W : Nat} (x : Signal dom (BitVec W)) := x
@[sparkle_module]
def exportMiddle {dom : DomainConfig} {W : Nat} (x : Signal dom (BitVec W)) := exportLeaf x
'''


def test_scalar_zero_selections_use_declared_types_and_preserve_values(tmp_path):
    sv = generate(tmp_path, '''import cktlean.Backend.Verilog
open cktlean.IR.AST cktlean.Backend.Verilog
def scalarSignals : List Port := [{name := "flag", ty := .bit}]
#guard lowerScalarSelections (.slice (.ref "flag") 1 0) scalarSignals == .slice (.ref "flag") 1 0
#guard lowerScalarSelections (.sliceDim (.ref "flag") (.parameter "W") (.literal 0)) scalarSignals ==
  .sliceDim (.ref "flag") (.parameter "W") (.literal 0)
def testModule : Module := {
  name := "scalar_selections"
  inputs := scalarSignals
  outputs := [{name := "a", ty := .bit}, {name := "b", ty := .bit}, {name := "c", ty := .bit}, {name := "d", ty := .bit}]
  wires := [{name := "temporary", ty := .bit}]
  body := [.assign "temporary" (.ref "flag"),
           .assign "a" (.slice (.ref "flag") 0 0),
           .assign "b" (.sliceDim (.ref "temporary") (.literal 0) (.literal 0)),
           .assignExpr (.slice (.ref "c") 0 0) (.index (.ref "temporary") (.const 0 1)),
           .generateFor "copy" "i" (.literal 0) (.literal 1)
             [.assignExpr (.sliceDim (.ref "d")
               (.sub (.add (.mul (.parameter "i") (.literal 1)) (.literal 1)) (.literal 1))
               (.mul (.parameter "i") (.literal 1)))
               (.sliceDim (.ref "temporary") (.parameter "i") (.parameter "i"))]]
}
#eval IO.println (toVerilog testModule)
''')
    assert "flag[" not in sv and "temporary[" not in sv
    tb = '''module tb;
      reg flag; wire a,b,c,d;
      scalar_selections dut(flag,a,b,c,d);
      task check; begin #1; if ({a,b,c,d} !== {4{flag}}) $fatal(1, "scalar selection changed value"); end endtask
      initial begin flag=0; check; flag=1; check; flag=1'bx; check; flag=1'bz; check; $finish; end
    endmodule'''
    compile_sv(tmp_path, sv + "\n" + tb, "tb")
    result = subprocess.run(["vvp", str(tmp_path / "export.vvp")], capture_output=True, text=True, timeout=10)
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.parametrize("parameterized", [False, True])
def test_plain_synthesis_command_exports_transitive_dependencies(tmp_path, parameterized):
    top = "exportTop"
    if parameterized:
        code = HIERARCHY + '''def exportTop {W : Nat} (x : Signal defaultDomain (BitVec W)) := exportMiddle x
#synthesizeParameterizedVerilog exportTop [W := 8]
'''
    else:
        code = HIERARCHY + '''def exportTop (x : Signal defaultDomain (BitVec 8)) := exportMiddle x
#synthesizeVerilog exportTop
'''
    sv = generate(tmp_path, code)
    assert sv.count("module exportLeaf ") == 1
    assert sv.count("module exportMiddle ") == 1
    assert sv.count("module exportTop ") == 1
    assert sv.index("module exportTop ") < sv.index("module exportLeaf ")
    for width in ([1, 3, 8, 13] if parameterized else [8]):
        compile_sv(tmp_path, sv, top, [("W", width)] if parameterized else [])
