import Sparkle.Compiler.Elab
import Tests.SymbolicParameterCircuits

#writeParameterizedCppSimDesign symbolicXor [W := 3] "/tmp/p3_cppsim_xor_w3.h"
#writeParameterizedCppSimDesign symbolicXor [W := 17] "/tmp/p3_cppsim_xor_w17.h"
#writeParameterizedCppSimDesign symbolicCastExtend [W := 17] "/tmp/p3_cppsim_cast_extend_w17.h"
#writeParameterizedCppSimDesign symbolicCastTrunc [W := 17] "/tmp/p3_cppsim_cast_trunc_w17.h"
#writeParameterizedCppSimDesign symbolicModulo [W := 17] "/tmp/p3_cppsim_modulo_w17.h"
#writeParameterizedCppSimDesign symbolicRepeatVector [W := 3, N := 4] "/tmp/p3_cppsim_repeat_w3_n4.h"
#writeParameterizedCppSimDesign symbolicRepeatVector [W := 17, N := 3] "/tmp/p3_cppsim_repeat_w17_n3.h"
#writeParameterizedCppSimDesign symbolicIotaVector1 [W := 4, N := 3] "/tmp/p3_cppsim_iota_w4_n3.h"
#writeParameterizedCppSimDesign symbolicIotaVector1 [W := 3, N := 5] "/tmp/p3_cppsim_iota_w3_n5.h"
#writeParameterizedCppSimDesign symbolicMapChunks [W := 3, N := 4] "/tmp/p3_cppsim_map_chunks_w3_n4.h"
#writeParameterizedCppSimDesign symbolicMapChunksWithIndex [W := 3, N := 4] "/tmp/p3_cppsim_map_chunks_indexed_w3_n4.h"
#writeParameterizedCppSimDesign symbolicMapChunksNarrow [N := 3] "/tmp/p3_cppsim_map_chunks_narrow_n3.h"
#writeParameterizedCppSimDesign symbolicMapChunksNarrow [N := 5] "/tmp/p3_cppsim_map_chunks_narrow_n5.h"
#writeParameterizedCppSimDesign symbolicMemory [ADDR_W := 2, DATA_W := 8] "/tmp/p3_cppsim_memory_a2_d8.h"
#writeParameterizedCppSimDesign symbolicMemory [ADDR_W := 4, DATA_W := 17] "/tmp/p3_cppsim_memory_a4_d17.h"
#writeParameterizedCppSimDesign symbolicXorHierarchy [W := 17] "/tmp/p3_cppsim_hierarchy_w17.h"
#writeParameterizedCppSimDesign symbolicGenerateNot [W := 3] "/tmp/p3_cppsim_generate_w3.h"
#writeParameterizedCppSimDesign symbolicGenerateNot [W := 17] "/tmp/p3_cppsim_generate_w17.h"
#writeParameterizedCppSimDesign symbolicLoopBundle [W := 3] "/tmp/p3_cppsim_loop_bundle_w3.h"
#writeParameterizedCppSimDesign symbolicLoopBundle [W := 17] "/tmp/p3_cppsim_loop_bundle_w17.h"
#writeParameterizedCppSimDesign symbolicPairLoop [W := 3] "/tmp/p3_cppsim_pair_loop_w3.h"
#writeParameterizedCppSimDesign symbolicPairLoop [W := 17] "/tmp/p3_cppsim_pair_loop_w17.h"
#writeParameterizedCppSimDesign symbolicDepthCompare [DEPTH := 8] "/tmp/p3_cppsim_depth_compare_d8.h"
#writeParameterizedCppSimDesign symbolicDepthCompare [DEPTH := 12] "/tmp/p3_cppsim_depth_compare_d12.h"
#writeParameterizedCppSimDesign symbolicDepthCompare [DEPTH := 16] "/tmp/p3_cppsim_depth_compare_d16.h"
#writeParameterizedCppSimDesign symbolicPopCount [W := 3] "/tmp/p3_cppsim_popcount_w3.h"
#writeParameterizedCppSimDesign symbolicPopCount [W := 17] "/tmp/p3_cppsim_popcount_w17.h"
#writeParameterizedCppSimDesign symbolicReverseBits [W := 3] "/tmp/p3_cppsim_reverse_w3.h"
#writeParameterizedCppSimDesign symbolicReverseBits [W := 17] "/tmp/p3_cppsim_reverse_w17.h"
#writeParameterizedCppSimDesign symbolicReverseBlocks [W := 16, BLOCKS := 2] "/tmp/p3_cppsim_reverse_blocks_w16_b2.h"
#writeParameterizedCppSimDesign symbolicReverseBlocks [W := 16, BLOCKS := 4] "/tmp/p3_cppsim_reverse_blocks_w16_b4.h"
