from __future__ import annotations

import shutil
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "agent"))

from cvdp_native_parameters import (  # noqa: E402
    native_plan_from_dict,
    native_plan_to_dict,
    parse_native_modules,
    select_native_core_module,
)
from cvdp_specialization import (  # noqa: E402
    FiniteParameterPlan,
    SpecializationCase,
)
from evaluator import (  # noqa: E402
    Evaluator,
    _record_failure,
    prepare_cvdp_native_parameter_design,
)
from search import build_user_message  # noqa: E402
from cktarchon import run as ckt_run  # noqa: E402


def _plan(widths: tuple[int, ...] = (3, 17, 65)) -> FiniteParameterPlan:
    return FiniteParameterPlan(
        design_name="native_xor",
        parameter_names=("WIDTH",),
        cases=tuple(
            SpecializationCase(
                parameters=(("WIDTH", width),),
                module_name=f"unused_{width}",
            )
            for width in widths
        ),
    )


GENERIC_XOR = """
// Generated by Sparkle HDL
module native_xor #(
    parameter integer WIDTH = 8
) (
    input logic [WIDTH-1:0] _gen_lhs,
    input logic [WIDTH-1:0] _gen_rhs,
    output logic [WIDTH-1:0] out
);
    assign out = _gen_lhs ^ _gen_rhs;
endmodule
"""


REF_XOR = """
module native_xor #(
    parameter WIDTH = 8
) (
    input logic [WIDTH-1:0] lhs,
    input logic [WIDTH-1:0] rhs,
    output logic [WIDTH-1:0] out
);
endmodule
"""


HARNESS = {
    "src/test_runner.py": """
        runner.build(parameters={"WIDTH": WIDTH})
        dut.lhs.value = 0
        dut.rhs.value = 0
        assert int(dut.out.value) == 0
    """,
}


EXPECTED_PORTS = [
    ("input", "logic [WIDTH-1:0]", "lhs"),
    ("input", "logic [WIDTH-1:0]", "rhs"),
    ("output", "logic [WIDTH-1:0]", "out"),
]


def _prepare(sv_code: str = GENERIC_XOR):
    return prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="native_xor",
        plan=_plan(),
        expected_ports=EXPECTED_PORTS,
        ref_code=REF_XOR,
        harness_files=HARNESS,
    )


def test_native_plan_round_trip_keeps_sweep_cases_without_p0_modules():
    payload = native_plan_to_dict(_plan())
    assert payload["mode"] == "native_parameter_sweep"
    assert payload["specialization_count"] == 0
    assert payload["sweep_case_count"] == 3
    assert all("module_name" not in row for row in payload["cases"])

    restored = native_plan_from_dict(payload)
    assert restored is not None
    assert restored.parameter_names == ("WIDTH",)
    assert [case.values for case in restored.cases] == [
        {"WIDTH": 3},
        {"WIDTH": 17},
        {"WIDTH": 65},
    ]


def test_parser_and_selector_find_the_parameter_owning_core():
    child = "module child(input logic x, output logic y); assign y=x; endmodule\n"
    modules = parse_native_modules(child + GENERIC_XOR)
    assert [module.name for module in modules] == ["child", "native_xor"]
    assert modules[1].parameter_names == ("WIDTH",)
    assert select_native_core_module(
        child + GENERIC_XOR,
        required_parameters=["WIDTH"],
        preferred_name="native_xor",
    ).name == "native_xor"


def test_generic_core_is_wrapped_with_explicit_parameter_forwarding():
    design, manifest = _prepare()
    assert design is not None, manifest
    assert manifest["contract_pass"] is True
    assert manifest["one_emitted_dut"] is True
    assert manifest["sweep_case_count"] == 3
    assert "module native_xor_sparkle_inner #(\n" in design
    assert "native_xor_sparkle_inner #(\n        .WIDTH(WIDTH)" in design
    assert len({row["sv_sha256"] for row in manifest["cases"]}) == 1
    assert manifest["sv_sha256"] == manifest["cases"][0]["sv_sha256"]


@pytest.mark.skipif(shutil.which("iverilog") is None, reason="iverilog unavailable")
def test_same_sv_elaborates_at_unseen_widths_3_17_and_65(tmp_path: Path):
    design, manifest = _prepare()
    assert design is not None, manifest
    sv_file = tmp_path / "native_xor.sv"
    sv_file.write_text(design, encoding="utf-8")

    passed, rows, detail, stage = Evaluator._run_native_parameter_elaboration(
        sv_file=sv_file,
        top_module="native_xor",
        plan=_plan(),
    )
    assert passed, detail
    assert stage == "verilog_elaboration"
    assert [row["verilog_elaboration"] for row in rows] == [
        "passed", "passed", "passed",
    ]


def test_fixed_width_inner_core_is_rejected_before_simulation():
    fixed = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    design, manifest = _prepare(fixed)
    assert design is None
    assert manifest["contract_pass"] is False
    assert "fixed/non-matching type" in manifest["error"]


def test_declaration_only_parameter_is_rejected_before_simulation():
    declaration_only = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    design, manifest = _prepare(declaration_only)
    assert design is None
    assert "declaration-only" in manifest["error"]


def test_missing_required_parameter_is_rejected_before_simulation():
    missing = GENERIC_XOR.replace(
        " #(\n    parameter integer WIDTH = 8\n)", ""
    ).replace("WIDTH-1", "7")
    design, manifest = _prepare(missing)
    assert design is None
    assert "no generated module owns every required native parameter" in manifest["error"]


def test_structured_diagnostic_records_stage_code_and_legacy_detail():
    result = {"detail": "", "failure_stage": None, "diagnostics": []}
    _record_failure(
        result,
        "parameter_contract",
        "fixed-width inner core",
        code="native_parameter_contract_failed",
    )
    assert result["detail"] == "fixed-width inner core"
    assert result["failure_stage"] == "parameter_contract"
    assert result["diagnostics"] == [{
        "stage": "parameter_contract",
        "message": "fixed-width inner core",
        "code": "native_parameter_contract_failed",
    }]


class _FakeRepl:
    def __init__(self, modules: list[str]):
        self.modules = modules

    def check_file(self, _path: Path):
        return SimpleNamespace(
            passed=True,
            complete=True,
            verilog_modules=self.modules,
            verilog=self.modules[0] if self.modules else None,
            error_text="",
        )


def _native_info(formal_contract=None):
    payload = native_plan_to_dict(_plan())
    payload["expected_ports"] = EXPECTED_PORTS
    payload["derived_parameter_names"] = []
    payload["reset_polarities"] = {}
    metadata = {
        "dataset": "cvdp",
        "native_parameter_sweep_plan": payload,
        "harness_files": HARNESS,
    }
    if formal_contract is not None:
        metadata["formal_parameter_contract"] = formal_contract
    return SimpleNamespace(
        design_name="native_xor",
        ref_code=REF_XOR,
        prompt_text="parameter WIDTH",
        metadata=metadata,
    )


@pytest.mark.skipif(shutil.which("iverilog") is None, reason="iverilog unavailable")
def test_evaluator_native_path_keeps_all_modules_and_writes_one_hash_manifest(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("-- checked by fake REPL\n")
    child = (
        "// Generated by Sparkle HDL\n"
        "module child(input logic x, output logic y); assign y=x; endmodule"
    )
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([child, GENERIC_XOR]),
    )
    observed = {}

    def fake_sim(prob_id, sv_code, module_name, ports, run_dir, **kwargs):
        observed.update({
            "prob_id": prob_id,
            "sv_code": sv_code,
            "module_name": module_name,
            "ports": ports,
            "direct_top": kwargs.get("direct_top"),
        })
        return "sim_pass", 0, "ok"

    monkeypatch.setattr(evaluator, "_run_sim_cvdp", fake_sim)
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info(),
    )

    assert result["compile_pass"] is True
    assert result["native_parameter_contract_pass"] is True
    assert result["native_parameter_elaboration_pass"] is True
    assert result["sim_status"] == "sim_pass"
    assert result["failure_stage"] is None
    assert result["formal_status"] == "unsupported"
    assert result["formal_coverage"] == "none"
    assert result["formal_family_covered"] is False
    assert observed["module_name"] == "native_xor"
    assert observed["direct_top"] is True
    assert "module child" in observed["sv_code"]
    assert ".WIDTH(WIDTH)" in observed["sv_code"]

    manifest_path = Path(result["native_parameter_manifest"])
    manifest = __import__("json").loads(manifest_path.read_text())
    assert manifest["all_cases_elaborated"] is True
    assert {row["verilog_elaboration"] for row in manifest["cases"]} == {"passed"}
    assert len({row["sv_sha256"] for row in manifest["cases"]}) == 1


def test_evaluator_classifies_fixed_inner_as_parameter_contract_failure(
    tmp_path: Path,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("-- checked by fake REPL\n")
    fixed = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([fixed]),
    )
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info(),
    )
    assert result["compile_pass"] is True
    assert result["sv_extracted"] is False
    assert result["sim_status"] == "not_run"
    assert result["failure_stage"] == "parameter_contract"
    assert result["diagnostics"][-1]["code"] == "native_parameter_contract_failed"


def test_explicit_generic_formal_policy_fails_closed_when_theorem_is_missing(
    tmp_path: Path,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("def no_proof := True\n")
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([GENERIC_XOR]),
        parameter_formal_policy="generic",
    )
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info({"generic_theorem": "native_xor_correct"}),
    )
    assert result["native_parameter_contract_pass"] is True
    assert result["formal_status"] == "incomplete"
    assert result["formal_family_covered"] is False
    assert result["sv_extracted"] is False
    assert result["sim_status"] == "not_run"
    assert result["failure_stage"] == "unsupported_backend"
    assert result["diagnostics"][-1]["code"] == "formal_parameter_policy_failed"


def test_runner_configures_native_metadata_and_prompt_without_p0_aliases():
    harness = {
        "src/test_runner.py": """
            import pytest

            def test_runner(WIDTH=8):
                runner.build(parameters={"WIDTH": WIDTH})
                dut.lhs.value = 0
                dut.rhs.value = 0
                int(dut.out.value)

            @pytest.mark.parametrize("WIDTH", [3, 17, 65])
            def test_sweep(WIDTH):
                test_runner(WIDTH=WIDTH)
        """,
    }
    info = SimpleNamespace(
        design_name="native_xor",
        ref_code=REF_XOR,
        prompt_text="parameter WIDTH; input lhs; input rhs; output out",
        metadata={"dataset": "cvdp", "harness_files": harness},
    )
    configured = ckt_run.configure_parameter_mode(
        info,
        finite_enabled=False,
        native_enabled=True,
    )
    assert "finite_parameter_plan" not in configured.metadata
    payload = configured.metadata["native_parameter_sweep_plan"]
    assert payload["mode"] == "native_parameter_sweep"
    assert [row["parameters"] for row in payload["cases"]] == [
        {"WIDTH": 3}, {"WIDTH": 8}, {"WIDTH": 17}, {"WIDTH": 65},
    ]

    prompt = build_user_message(
        "native_case",
        has_repl=True,
        info=configured,
        dataset_name="cvdp",
    )
    assert "### Native Parameter Sweep (P3)" in prompt
    assert "#synthesizeParameterizedVerilog native_xor [WIDTH := 3]" in prompt
    assert "Do not enumerate sweep values" in prompt
    assert "Repeat the eta-expanded alias" not in prompt


def test_cli_rejects_p0_and_p3_parameter_modes_together(
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(sys, "argv", [
        "cktarchon/run.py",
        "--results-dir", "/tmp/result",
        "--finite-parameter-specialization",
        "--native-parameter-sweep",
    ])
    with pytest.raises(SystemExit) as exc:
        ckt_run.parse_args()
    assert exc.value.code == 2
