from __future__ import annotations

import shutil
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "agent"))

from cvdp_native_parameters import (  # noqa: E402
    format_native_parameter_contract,
    native_plan_from_dict,
    native_plan_to_dict,
    parse_native_modules,
    select_native_core_module,
)
from cvdp_specialization import (  # noqa: E402
    FiniteParameterPlan,
    SpecializationCase,
)
from evaluator import (  # noqa: E402
    Evaluator,
    _iverilog_failure_stage,
    _record_failure,
    prepare_cvdp_native_parameter_design,
)
from search import build_user_message  # noqa: E402
from cktarchon import run as ckt_run  # noqa: E402


def _plan(widths: tuple[int, ...] = (3, 17, 65)) -> FiniteParameterPlan:
    return FiniteParameterPlan(
        design_name="native_xor",
        parameter_names=("WIDTH",),
        cases=tuple(
            SpecializationCase(
                parameters=(("WIDTH", width),),
                module_name=f"unused_{width}",
            )
            for width in widths
        ),
    )


GENERIC_XOR = """
// Generated by Sparkle HDL
module native_xor #(
    parameter integer WIDTH = 8
) (
    input logic [WIDTH-1:0] _gen_lhs,
    input logic [WIDTH-1:0] _gen_rhs,
    output logic [WIDTH-1:0] out
);
    assign out = _gen_lhs ^ _gen_rhs;
endmodule
"""


REF_XOR = """
module native_xor #(
    parameter WIDTH = 8
) (
    input logic [WIDTH-1:0] lhs,
    input logic [WIDTH-1:0] rhs,
    output logic [WIDTH-1:0] out
);
endmodule
"""


HARNESS = {
    "src/test_runner.py": """
        runner.build(parameters={"WIDTH": WIDTH})
        dut.lhs.value = 0
        dut.rhs.value = 0
        assert int(dut.out.value) == 0
    """,
}


EXPECTED_PORTS = [
    ("input", "logic [WIDTH-1:0]", "lhs"),
    ("input", "logic [WIDTH-1:0]", "rhs"),
    ("output", "logic [WIDTH-1:0]", "out"),
]


def _prepare(sv_code: str = GENERIC_XOR):
    return prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="native_xor",
        plan=_plan(),
        expected_ports=EXPECTED_PORTS,
        ref_code=REF_XOR,
        harness_files=HARNESS,
    )


def _hamming_plan() -> FiniteParameterPlan:
    return FiniteParameterPlan(
        design_name="hamming_tx",
        parameter_names=("DATA_WIDTH", "PARITY_BIT"),
        cases=tuple(
            SpecializationCase(
                parameters=(("DATA_WIDTH", data), ("PARITY_BIT", parity)),
                module_name=f"unused_{data}_{parity}",
            )
            for data, parity in ((4, 3), (8, 4), (16, 5))
        ),
    )


GENERIC_HAMMING = """
// Generated by Sparkle HDL
module hamming_tx #(
    parameter integer DATA_WIDTH = 4,
    parameter integer PARITY_BIT = 3
) (
    input logic [DATA_WIDTH-1:0] _gen_data_in,
    output logic [DATA_WIDTH+PARITY_BIT:0] out
);
    assign out = {{(PARITY_BIT+1){1'b0}}, _gen_data_in};
endmodule
"""


HAMMING_REF = """
module hamming_tx(
    input logic [DATA_WIDTH-1:0] data_in,
    output logic [ENCODED_DATA-1:0] data_out
);
endmodule
"""


HAMMING_HARNESS = {
    "src/test_runner.py": """
        runner.build(parameters={"DATA_WIDTH": DATA_WIDTH, "PARITY_BIT": PARITY_BIT})
        dut.data_in.value = 0
        int(dut.data_out.value)
    """,
    "src/tx_test.py": "ENCODED_DATA = PARITY_BIT + DATA_WIDTH + 1",
}


HAMMING_PORTS = [
    ("input", "logic [DATA_WIDTH-1:0]", "data_in"),
    ("output", "logic [ENCODED_DATA-1:0]", "data_out"),
]


def test_native_plan_round_trip_keeps_sweep_cases_without_p0_modules():
    payload = native_plan_to_dict(_plan())
    assert payload["mode"] == "native_parameter_sweep"
    assert payload["specialization_count"] == 0
    assert payload["sweep_case_count"] == 3
    assert all("module_name" not in row for row in payload["cases"])

    restored = native_plan_from_dict(payload)
    assert restored is not None
    assert restored.parameter_names == ("WIDTH",)
    assert [case.values for case in restored.cases] == [
        {"WIDTH": 3},
        {"WIDTH": 17},
        {"WIDTH": 65},
    ]


def test_native_contract_requires_design_emission_for_hierarchical_helpers():
    contract = format_native_parameter_contract(_plan())
    assert "#synthesizeParameterizedVerilogDesign" in contract
    assert "named `@[sparkle_module]` helper" in contract
    assert "unknown module types" in contract


def test_iverilog_runtime_failures_are_not_reported_as_rtl_errors():
    assert _iverilog_failure_stage(
        "sh: /toolcache/usr/x86_64-linux-gnu/ivl/ivlpp: not found"
    ) == "infrastructure"
    assert _iverilog_failure_stage(
        "dut.sv:12: syntax error"
    ) == "verilog_elaboration"


def test_parser_and_selector_find_the_parameter_owning_core():
    child = "module child(input logic x, output logic y); assign y=x; endmodule\n"
    modules = parse_native_modules(child + GENERIC_XOR)
    assert [module.name for module in modules] == ["child", "native_xor"]
    assert modules[1].parameter_names == ("WIDTH",)
    assert select_native_core_module(
        child + GENERIC_XOR,
        required_parameters=["WIDTH"],
        preferred_name="native_xor",
    ).name == "native_xor"


def test_generic_core_is_wrapped_with_explicit_parameter_forwarding():
    design, manifest = _prepare()
    assert design is not None, manifest
    assert manifest["contract_pass"] is True
    assert manifest["one_emitted_dut"] is True
    assert manifest["sweep_case_count"] == 3
    assert "module native_xor_sparkle_inner #(\n" in design
    assert "native_xor_sparkle_inner #(\n        .WIDTH(WIDTH)" in design
    assert len({row["sv_sha256"] for row in manifest["cases"]}) == 1
    assert manifest["sv_sha256"] == manifest["cases"][0]["sv_sha256"]


def test_native_wrapper_maps_symbolic_packed_field_by_semantics():
    plan = FiniteParameterPlan(
        design_name="square_root_seq",
        parameter_names=("WIDTH",),
        cases=tuple(
            SpecializationCase(
                parameters=(("WIDTH", width),),
                module_name=f"unused_{width}",
            )
            for width in (2, 4, 8, 16)
        ),
    )
    sv_code = """
module square_root_seq #(parameter integer WIDTH = 2) (
    input logic [WIDTH-1:0] _gen_num,
    output logic [(1 + (WIDTH / 2))-1:0] out
);
    logic _gen_done;
    logic [(WIDTH / 2)-1:0] _gen_regRoot;
    assign _gen_done = 1'b0;
    assign _gen_regRoot = _gen_num[(WIDTH / 2)-1:0];
    assign out = {_gen_done, _gen_regRoot};
endmodule
"""
    ref_code = """
module square_root_seq #(parameter integer WIDTH = 2) (
    input logic [WIDTH-1:0] num,
    output logic done,
    output logic [WIDTH/2-1:0] final_root
);
endmodule
"""
    expected_ports = [
        ("input", "logic [WIDTH-1:0]", "num"),
        ("output", "logic", "done"),
        ("output", "logic [WIDTH/2-1:0]", "final_root"),
    ]
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="square_root_seq",
        plan=plan,
        expected_ports=expected_ports,
        ref_code=ref_code,
        harness_files={
            "src/test_runner.py": "runner.build(parameters={\"WIDTH\": WIDTH})",
        },
    )
    assert design is not None, manifest
    assert manifest["contract_pass"] is True
    assert "assign {done, final_root} = out_wire;" in design


def test_native_wrapper_maps_renamed_symbolic_fields_by_sweep_width_and_order(
    tmp_path: Path,
):
    plan = FiniteParameterPlan(
        design_name="parking",
        parameter_names=("TOTAL_SPACES",),
        cases=tuple(
            SpecializationCase(
                parameters=(("TOTAL_SPACES", spaces),),
                module_name=f"unused_{spaces}",
            )
            for spaces in (9, 12, 14)
        ),
    )
    sv_code = """
module parking #(parameter integer TOTAL_SPACES = 9) (
    input logic _gen_reset,
    output logic [($clog2(TOTAL_SPACES) + ($clog2(TOTAL_SPACES) + 1))-1:0] out
);
    logic [$clog2(TOTAL_SPACES)-1:0] _gen_available;
    logic [$clog2(TOTAL_SPACES)-1:0] _tmp_loop_body;
    logic _gen_status;
    assign out = {_gen_available, {_tmp_loop_body, _gen_status}};
endmodule
"""
    expected_ports = [
        ("input", "logic", "reset"),
        ("output", "logic [log2(TOTAL_SPACES)-1:0]", "available_spaces"),
        ("output", "logic [log2(TOTAL_SPACES)-1:0]", "count_car"),
        ("output", "logic", "led_status"),
    ]
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="parking",
        plan=plan,
        expected_ports=expected_ports,
        ref_code="""
module parking #(parameter integer TOTAL_SPACES = 9) (
    input logic reset,
    output logic [log2(TOTAL_SPACES)-1:0] available_spaces,
    output logic [log2(TOTAL_SPACES)-1:0] count_car,
    output logic led_status
); endmodule
""",
        harness_files={
            "src/test_runner.py": (
                "runner.build(parameters={'TOTAL_SPACES': TOTAL_SPACES}); "
                "dut.available_spaces.value; dut.count_car.value; dut.led_status.value"
            ),
        },
    )
    assert design is not None, manifest
    assert manifest["contract_pass"] is True
    assert (
        "assign {available_spaces, count_car, led_status} = out_wire;"
        in design
    )
    assert "logic [$clog2(TOTAL_SPACES)-1:0] available_spaces" in design
    assert "logic [$clog2(TOTAL_SPACES)-1:0] count_car" in design

    if shutil.which("iverilog") is not None:
        sv_file = tmp_path / "parking.sv"
        sv_file.write_text(design, encoding="utf-8")
        passed, rows, detail, stage = Evaluator._run_native_parameter_elaboration(
            sv_file=sv_file,
            top_module="parking",
            plan=plan,
        )
        assert passed, detail
        assert stage == "verilog_elaboration"
        assert {row["verilog_elaboration"] for row in rows} == {"passed"}


def test_native_wrapper_maps_real_car_parking_seven_output_bundle():
    plan = FiniteParameterPlan(
        design_name="car_parking_system",
        parameter_names=("TOTAL_SPACES",),
        cases=tuple(
            SpecializationCase(
                parameters=(("TOTAL_SPACES", spaces),),
                module_name=f"unused_{spaces}",
            )
            for spaces in (9, 12, 14)
        ),
    )
    sv_code = """
module car_parking_system #(parameter integer TOTAL_SPACES = 9) (
    input logic _gen_reset,
    input logic _gen_vehicle_entry_sensor,
    input logic _gen_vehicle_exit_sensor,
    input logic clk,
    input logic rst,
    output logic [($clog2(TOTAL_SPACES) + ($clog2(TOTAL_SPACES) + 29))-1:0] out
);
    logic [$clog2(TOTAL_SPACES)-1:0] _gen_available;
    logic [$clog2(TOTAL_SPACES)-1:0] _tmp_loop_body_8;
    logic _gen_led;
    logic [6:0] _gen_availableTensDisplay;
    logic [6:0] _gen_availableUnitsDisplay;
    logic [6:0] _gen_countTensDisplay;
    logic [6:0] _gen_countUnitsDisplay;
    logic [13:0] _tmp_b_893;
    logic [20:0] _tmp_b_894;
    logic [27:0] _tmp_b_895;
    logic [28:0] _tmp_b_896;
    logic [($clog2(TOTAL_SPACES) + 29)-1:0] _tmp_b_897;
    logic [($clog2(TOTAL_SPACES) + ($clog2(TOTAL_SPACES) + 29))-1:0] _tmp_result_898;
    assign _tmp_b_893 = {_gen_countTensDisplay, _gen_countUnitsDisplay};
    assign _tmp_b_894 = {_gen_availableUnitsDisplay, _tmp_b_893};
    assign _tmp_b_895 = {_gen_availableTensDisplay, _tmp_b_894};
    assign _tmp_b_896 = {_gen_led, _tmp_b_895};
    assign _tmp_b_897 = {_tmp_loop_body_8, _tmp_b_896};
    assign _tmp_result_898 = {_gen_available, _tmp_b_897};
    assign out = _tmp_result_898;
endmodule
"""
    expected_outputs = [
        ("output", "logic [$clog2(TOTAL_SPACES+1)-1:0]", "available_spaces"),
        ("output", "logic [$clog2(TOTAL_SPACES+1)-1:0]", "count_car"),
        ("output", "logic", "led_status"),
        ("output", "logic [6:0]", "seven_seg_display_available_tens"),
        ("output", "logic [6:0]", "seven_seg_display_available_units"),
        ("output", "logic [6:0]", "seven_seg_display_count_tens"),
        ("output", "logic [6:0]", "seven_seg_display_count_units"),
    ]
    expected_ports = [
        expected_outputs[0],
        ("input", "logic", "clk"),
        expected_outputs[1],
        expected_outputs[2],
        ("input", "logic", "reset"),
        *expected_outputs[3:],
        ("input", "logic", "vehicle_entry_sensor"),
        ("input", "logic", "vehicle_exit_sensor"),
    ]
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="car_parking_system",
        plan=plan,
        expected_ports=expected_ports,
        ref_code="(no public reference Verilog available)",
        harness_files={
            "src/test_runner.py": (
                "parameter_defines = {'TOTAL_SPACES': TOTAL_SPACES}; "
                "runner.build(parameters=parameter_defines); "
                "dut.available_spaces.value; dut.count_car.value; dut.led_status.value"
            ),
        },
    )
    assert design is not None, manifest
    assert manifest["contract_pass"] is True
    assert (
        "assign {available_spaces, count_car, led_status, "
        "seven_seg_display_available_tens, seven_seg_display_available_units, "
        "seven_seg_display_count_tens, seven_seg_display_count_units} = out_wire;"
        in design
    )


def test_native_wrapper_rejects_positional_bundle_when_any_sweep_width_differs():
    plan = FiniteParameterPlan(
        design_name="bad_bundle",
        parameter_names=("WIDTH",),
        cases=tuple(
            SpecializationCase(
                parameters=(("WIDTH", width),),
                module_name=f"unused_{width}",
            )
            for width in (3, 17)
        ),
    )
    sv_code = """
module bad_bundle #(parameter integer WIDTH = 3) (
    output logic [(WIDTH + WIDTH)-1:0] out
);
    logic [WIDTH-1:0] _tmp_first;
    logic [WIDTH-1:0] _tmp_second;
    assign out = {_tmp_first, _tmp_second};
endmodule
"""
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=sv_code,
        design_name="bad_bundle",
        plan=plan,
        expected_ports=[
            ("output", "logic [WIDTH-1:0]", "first"),
            ("output", "logic [WIDTH:0]", "second"),
        ],
        ref_code="""
module bad_bundle #(parameter integer WIDTH = 3) (
    output logic [WIDTH-1:0] first,
    output logic [WIDTH:0] second
); endmodule
""",
        harness_files={
            "src/test_runner.py": (
                "runner.build(parameters={'WIDTH': WIDTH}); "
                "dut.first.value; dut.second.value"
            ),
        },
    )
    assert design is None
    assert manifest["contract_pass"] is False
    assert "could not validate derived width" in manifest["error"]

@pytest.mark.skipif(shutil.which("iverilog") is None, reason="iverilog unavailable")
def test_same_sv_elaborates_at_unseen_widths_3_17_and_65(tmp_path: Path):
    design, manifest = _prepare()
    assert design is not None, manifest
    sv_file = tmp_path / "native_xor.sv"
    sv_file.write_text(design, encoding="utf-8")

    passed, rows, detail, stage = Evaluator._run_native_parameter_elaboration(
        sv_file=sv_file,
        top_module="native_xor",
        plan=_plan(),
    )
    assert passed, detail
    assert stage == "verilog_elaboration"
    assert [row["verilog_elaboration"] for row in rows] == [
        "passed", "passed", "passed",
    ]


def test_fixed_width_inner_core_is_rejected_before_simulation():
    fixed = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    design, manifest = _prepare(fixed)
    assert design is None
    assert manifest["contract_pass"] is False
    assert "fixed/non-matching type" in manifest["error"]


def test_declaration_only_parameter_is_rejected_before_simulation():
    declaration_only = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    design, manifest = _prepare(declaration_only)
    assert design is None
    assert "declaration-only" in manifest["error"]


def test_missing_required_parameter_is_rejected_before_simulation():
    missing = GENERIC_XOR.replace(
        " #(\n    parameter integer WIDTH = 8\n)", ""
    ).replace("WIDTH-1", "7")
    design, manifest = _prepare(missing)
    assert design is None
    assert "no generated module owns every required native parameter" in manifest["error"]


def test_derived_interface_width_is_local_not_an_independent_sweep_parameter():
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=GENERIC_HAMMING,
        design_name="hamming_tx",
        plan=_hamming_plan(),
        expected_ports=HAMMING_PORTS,
        ref_code=HAMMING_REF,
        harness_files=HAMMING_HARNESS,
        derived_parameter_names=["ENCODED_DATA"],
    )
    assert design is not None, manifest
    assert manifest["required_parameters"] == ["DATA_WIDTH", "PARITY_BIT"]
    assert manifest["derived_parameters"] == ["ENCODED_DATA"]
    assert manifest["derived_parameter_expressions"] == {
        "ENCODED_DATA": "DATA_WIDTH + PARITY_BIT + 1"
    }
    top = design[design.rindex("module hamming_tx"):]
    assert "localparam integer ENCODED_DATA = DATA_WIDTH + PARITY_BIT + 1" in top
    assert ".DATA_WIDTH(DATA_WIDTH)" in top
    assert ".PARITY_BIT(PARITY_BIT)" in top
    assert ".ENCODED_DATA(" not in top


def test_derived_interface_width_mismatch_is_rejected_across_sweep_cases():
    wrong_width = GENERIC_HAMMING.replace(
        "[DATA_WIDTH+PARITY_BIT:0]", "[DATA_WIDTH+PARITY_BIT-1:0]"
    )
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=wrong_width,
        design_name="hamming_tx",
        plan=_hamming_plan(),
        expected_ports=HAMMING_PORTS,
        ref_code=HAMMING_REF,
        harness_files=HAMMING_HARNESS,
        derived_parameter_names=["ENCODED_DATA"],
    )
    assert design is None
    assert "derived width mismatch" in manifest["error"]


@pytest.mark.skipif(shutil.which("iverilog") is None, reason="iverilog unavailable")
def test_derived_localparam_wrapper_elaborates_every_public_case(tmp_path: Path):
    design, manifest = prepare_cvdp_native_parameter_design(
        sv_code=GENERIC_HAMMING,
        design_name="hamming_tx",
        plan=_hamming_plan(),
        expected_ports=HAMMING_PORTS,
        ref_code=HAMMING_REF,
        harness_files=HAMMING_HARNESS,
        derived_parameter_names=["ENCODED_DATA"],
    )
    assert design is not None, manifest
    sv_file = tmp_path / "hamming_tx.sv"
    sv_file.write_text(design, encoding="utf-8")
    passed, rows, detail, stage = Evaluator._run_native_parameter_elaboration(
        sv_file=sv_file,
        top_module="hamming_tx",
        plan=_hamming_plan(),
    )
    assert passed, detail
    assert stage == "verilog_elaboration"
    assert {row["verilog_elaboration"] for row in rows} == {"passed"}


def test_structured_diagnostic_records_stage_code_and_legacy_detail():
    result = {"detail": "", "failure_stage": None, "diagnostics": []}
    _record_failure(
        result,
        "parameter_contract",
        "fixed-width inner core",
        code="native_parameter_contract_failed",
    )
    assert result["detail"] == "fixed-width inner core"
    assert result["failure_stage"] == "parameter_contract"
    assert result["diagnostics"] == [{
        "stage": "parameter_contract",
        "message": "fixed-width inner core",
        "code": "native_parameter_contract_failed",
    }]


class _FakeRepl:
    def __init__(self, modules: list[str]):
        self.modules = modules

    def check_file(self, _path: Path):
        return SimpleNamespace(
            passed=True,
            complete=True,
            verilog_modules=self.modules,
            verilog=self.modules[0] if self.modules else None,
            error_text="",
        )


def _native_info(formal_contract=None):
    payload = native_plan_to_dict(_plan())
    payload["expected_ports"] = EXPECTED_PORTS
    payload["derived_parameter_names"] = []
    payload["reset_polarities"] = {}
    metadata = {
        "dataset": "cvdp",
        "native_parameter_sweep_plan": payload,
        "harness_files": HARNESS,
    }
    if formal_contract is not None:
        metadata["formal_parameter_contract"] = formal_contract
    return SimpleNamespace(
        design_name="native_xor",
        ref_code=REF_XOR,
        prompt_text="parameter WIDTH",
        metadata=metadata,
    )


@pytest.mark.skipif(shutil.which("iverilog") is None, reason="iverilog unavailable")
def test_evaluator_native_path_keeps_all_modules_and_writes_one_hash_manifest(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("-- checked by fake REPL\n")
    child = (
        "// Generated by Sparkle HDL\n"
        "module child(input logic x, output logic y); assign y=x; endmodule"
    )
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([child, GENERIC_XOR]),
    )
    observed = {}

    def fake_sim(prob_id, sv_code, module_name, ports, run_dir, **kwargs):
        observed.update({
            "prob_id": prob_id,
            "sv_code": sv_code,
            "module_name": module_name,
            "ports": ports,
            "direct_top": kwargs.get("direct_top"),
        })
        return "sim_pass", 0, "ok"

    monkeypatch.setattr(evaluator, "_run_sim_cvdp", fake_sim)
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info(),
    )

    assert result["compile_pass"] is True
    assert result["native_parameter_contract_pass"] is True
    assert result["native_parameter_elaboration_pass"] is True
    assert result["sim_status"] == "sim_pass"
    assert result["failure_stage"] is None
    assert result["formal_status"] == "unsupported"
    assert result["formal_coverage"] == "none"
    assert result["formal_family_covered"] is False
    assert observed["module_name"] == "native_xor"
    assert observed["direct_top"] is True
    assert "module child" in observed["sv_code"]
    assert ".WIDTH(WIDTH)" in observed["sv_code"]

    manifest_path = Path(result["native_parameter_manifest"])
    manifest = __import__("json").loads(manifest_path.read_text())
    assert manifest["all_cases_elaborated"] is True
    assert {row["verilog_elaboration"] for row in manifest["cases"]} == {"passed"}
    assert len({row["sv_sha256"] for row in manifest["cases"]}) == 1


def test_evaluator_classifies_fixed_inner_as_parameter_contract_failure(
    tmp_path: Path,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("-- checked by fake REPL\n")
    fixed = GENERIC_XOR.replace("[WIDTH-1:0]", "[7:0]")
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([fixed]),
    )
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info(),
    )
    assert result["compile_pass"] is True
    assert result["sv_extracted"] is False
    assert result["sim_status"] == "not_run"
    assert result["failure_stage"] == "parameter_contract"
    assert result["diagnostics"][-1]["code"] == "native_parameter_contract_failed"


def test_evaluator_reports_native_ppa_per_case_without_a_default_metric(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("-- checked by fake REPL\n")
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([GENERIC_XOR]),
        enable_synth=True,
        parameter_ppa_policy="per_configuration",
    )
    monkeypatch.setattr(
        evaluator,
        "_run_native_parameter_elaboration",
        lambda **_kwargs: (
            True,
            [
                {"parameters": case.values, "verilog_elaboration": "passed"}
                for case in _plan().cases
            ],
            "ok",
            "verilog_elaboration",
        ),
    )
    monkeypatch.setattr(
        evaluator,
        "_run_sim_cvdp",
        lambda *_args, **_kwargs: ("sim_pass", 0, "ok"),
    )
    widths = iter((3, 17, 65))
    calls = []

    def fake_synth(case_id, concrete_sv, top_module, case_dir):
        width = next(widths)
        calls.append((case_id, concrete_sv, top_module, case_dir))
        top = concrete_sv[concrete_sv.rindex("module native_xor"):]
        assert f"WIDTH = {width}" in top
        return {
            "synth_pass": True,
            "area_um2": float(width),
            "cell_count": width,
            "wns_ns": None,
            "power_uw": None,
        }

    monkeypatch.setattr(evaluator, "_run_synthesis", fake_synth)
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info(),
    )

    assert len(calls) == 3
    assert result["sim_status"] == "sim_pass"
    assert result["synth_pass"] is True
    assert result["ppa_status"] == "passed"
    assert result["ppa_coverage"] == "all_public_configurations"
    assert result["ppa_family_covered"] is True
    assert result["area_um2"] is None
    assert [row["area_um2"] for row in result["ppa_case_results"]] == [3.0, 17.0, 65.0]
    manifest = __import__("json").loads(
        Path(result["ppa_parameter_manifest"]).read_text()
    )
    assert manifest["source_sv_sha256"] == manifest["cases"][0]["source_sv_sha256"]
    assert len({row["concrete_sv_sha256"] for row in manifest["cases"]}) == 3


def test_explicit_generic_formal_policy_fails_closed_when_theorem_is_missing(
    tmp_path: Path,
):
    generated = tmp_path / "Generated"
    generated.mkdir()
    (generated / "native_case.lean").write_text("def no_proof := True\n")
    evaluator = Evaluator(
        project_root=tmp_path,
        dataset="cvdp",
        dataset_obj=object(),
        lean_repl=_FakeRepl([GENERIC_XOR]),
        parameter_formal_policy="generic",
    )
    result = evaluator.evaluate(
        "native_case",
        tmp_path / "run",
        problem_info=_native_info({"generic_theorem": "native_xor_correct"}),
    )
    assert result["native_parameter_contract_pass"] is True
    assert result["formal_status"] == "incomplete"
    assert result["formal_family_covered"] is False
    assert result["sv_extracted"] is False
    assert result["sim_status"] == "not_run"
    assert result["failure_stage"] == "unsupported_backend"
    assert result["diagnostics"][-1]["code"] == "formal_parameter_policy_failed"


def test_runner_configures_native_metadata_and_prompt_without_p0_aliases():
    harness = {
        "src/test_runner.py": """
            import pytest

            def test_runner(WIDTH=8):
                runner.build(parameters={"WIDTH": WIDTH})
                dut.lhs.value = 0
                dut.rhs.value = 0
                int(dut.out.value)

            @pytest.mark.parametrize("WIDTH", [3, 17, 65])
            def test_sweep(WIDTH):
                test_runner(WIDTH=WIDTH)
        """,
    }
    info = SimpleNamespace(
        design_name="native_xor",
        ref_code=REF_XOR,
        prompt_text="parameter WIDTH; input lhs; input rhs; output out",
        metadata={"dataset": "cvdp", "harness_files": harness},
    )
    configured = ckt_run.configure_parameter_mode(
        info,
        finite_enabled=False,
        native_enabled=True,
    )
    assert "finite_parameter_plan" not in configured.metadata
    payload = configured.metadata["native_parameter_sweep_plan"]
    assert payload["mode"] == "native_parameter_sweep"
    assert [row["parameters"] for row in payload["cases"]] == [
        {"WIDTH": 3}, {"WIDTH": 8}, {"WIDTH": 17}, {"WIDTH": 65},
    ]

    prompt = build_user_message(
        "native_case",
        has_repl=True,
        info=configured,
        dataset_name="cvdp",
    )
    assert "### Native Parameter Sweep (P3)" in prompt
    assert "#synthesizeParameterizedVerilog native_xor [WIDTH := 3]" in prompt
    assert "Do not enumerate sweep values" in prompt
    assert "direct implicit top-level Nat binder" in prompt
    assert "def native_xor {dom : DomainConfig} {WIDTH : Nat}" in prompt
    assert "Keep every {NAME : Nat} binder in the exact def header" in prompt
    assert "#synthesizeParameterizedVerilogDesign" in prompt
    assert "named `@[sparkle_module]` helper" in prompt
    assert "Repeat the eta-expanded alias" not in prompt


def test_runner_carries_derived_widths_into_generation_and_repair_prompts():
    harness = {
        "src/test_runner.py": """
            import pytest

            @pytest.mark.parametrize(
                "DATA_WIDTH,PARITY_BIT",
                [(4, 3), (8, 4), (16, 5)],
            )
            def test_runner(DATA_WIDTH, PARITY_BIT):
                runner.build(parameters={
                    "DATA_WIDTH": DATA_WIDTH,
                    "PARITY_BIT": PARITY_BIT,
                })
                dut.data_in.value = 0
                int(dut.data_out.value)

            ENCODED_DATA = DATA_WIDTH + PARITY_BIT + 1
        """,
    }
    info = SimpleNamespace(
        design_name="hamming_tx",
        ref_code=HAMMING_REF,
        prompt_text="""
            ### Parameters
            - `DATA_WIDTH`: source data width
            - `PARITY_BIT`: parity-bit count
            - `ENCODED_DATA`: DATA_WIDTH + PARITY_BIT + 1

            ### Inputs
            - `data_in [DATA_WIDTH-1:0]`

            ### Outputs
            - `data_out [ENCODED_DATA-1:0]`
        """,
        metadata={"dataset": "cvdp", "harness_files": harness},
    )

    configured = ckt_run.configure_parameter_mode(
        info,
        finite_enabled=False,
        native_enabled=True,
    )
    payload = configured.metadata["native_parameter_sweep_plan"]
    assert payload["parameter_names"] == ["DATA_WIDTH", "PARITY_BIT"]
    assert payload["derived_parameter_names"] == ["ENCODED_DATA"]
    assert payload["derived_parameter_expressions"] == {
        "ENCODED_DATA": "DATA_WIDTH + PARITY_BIT + 1"
    }

    system_prompt = ckt_run.build_system_prompt(
        "base skill",
        "cvdp_hamming",
        configured,
    )
    assert "Retain these Nat binders as native SystemVerilog parameters: DATA_WIDTH, PARITY_BIT." in system_prompt
    assert "ENCODED_DATA = DATA_WIDTH + PARITY_BIT + 1" in system_prompt
    assert "not separate sweep binders" in system_prompt

    user_prompt = build_user_message(
        "cvdp_hamming",
        has_repl=True,
        info=configured,
        dataset_name="cvdp",
    )
    assert "### Derived Interface Dimensions" in user_prompt
    assert "`ENCODED_DATA = DATA_WIDTH + PARITY_BIT + 1`" in user_prompt
    assert "not independent sweep parameters" in user_prompt


def test_cli_rejects_p0_and_p3_parameter_modes_together(
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(sys, "argv", [
        "cktarchon/run.py",
        "--results-dir", "/tmp/result",
        "--finite-parameter-specialization",
        "--native-parameter-sweep",
    ])
    with pytest.raises(SystemExit) as exc:
        ckt_run.parse_args()
    assert exc.value.code == 2


def test_cli_requires_an_active_native_ppa_flow(
    monkeypatch: pytest.MonkeyPatch,
):
    base = [
        "cktarchon/run.py",
        "--results-dir", "/tmp/result",
        "--native-parameter-sweep",
        "--require-native-ppa",
    ]
    monkeypatch.setattr(sys, "argv", base)
    with pytest.raises(SystemExit) as exc:
        ckt_run.parse_args()
    assert exc.value.code == 2

    monkeypatch.setattr(sys, "argv", [*base, "--synth"])
    args = ckt_run.parse_args()
    assert args.require_native_ppa is True
    assert args.synth is True


def test_native_parameter_skill_overrides_concrete_width_advice():
    from search import load_skill

    skill = load_skill()
    assert "Native P3 Symbolic Parameters" in skill
    assert "this section overrides the" in skill
    assert "implicit binder: {WIDTH : Nat}" in skill
    assert "replace WIDTH by a concrete numeral" in skill
    assert "#synthesizeParameterizedVerilog exampleNativeXor [WIDTH := 8]" in skill
