"""
Lean 4 REPL client — persistent process with JSON protocol.

Wraps `lake exe repl` (leanprover-community/repl) to provide fast incremental
Lean compilation. The prelude (import Sparkle + opens) is loaded once and cached
as `env=0`; subsequent code is verified incrementally against that env.

Thread-safety: each LeanREPL instance manages its own subprocess. For concurrent
workers, create one instance per worker or use LeanREPLPool.
"""
from __future__ import annotations

import json
import os
import selectors
import signal
import threading
import time
import subprocess
from pathlib import Path
from dataclasses import dataclass, field


LAKE_PATH = os.environ.get("LAKE_PATH", os.path.expanduser("~/.elan/bin/lake"))

SPARKLE_PRELUDE = """\
import Sparkle
import Sparkle.Compiler.Elab

open Sparkle.Core.Domain
open Sparkle.Core.Signal
"""

# Default timeout for a single REPL command (seconds)
DEFAULT_TIMEOUT = 120


@dataclass
class REPLResult:
    """Parsed result from a REPL command."""
    passed: bool           # No errors
    complete: bool         # No errors AND no sorry
    errors: list[dict]     # Error messages
    warnings: list[dict]   # Warning messages
    infos: list[dict]      # Info messages (includes generated Verilog)
    sorries: list[dict]    # Sorry placeholders (with goal states)
    tactics: list[dict]    # Per-tactic info (when allTactics=True)
    env: int | None        # Opaque environment handle for incremental use
    verilog: str | None    # Extracted Verilog output (if any)
    verilog_modules: list[str]  # Every generated Verilog info block
    elapsed: float         # Time in seconds
    raw: dict | None       # Raw JSON response

    @property
    def error_text(self) -> str:
        """Format all errors as a single string."""
        lines = []
        for err in self.errors:
            pos = err.get("pos", {})
            loc = f"{pos.get('line', '?')}:{pos.get('column', '?')}"
            lines.append(f"[error {loc}] {err.get('data', '')}")
        return "\n".join(lines)

    @property
    def summary(self) -> str:
        """One-line summary for logging."""
        if self.passed:
            tag = "COMPLETE" if self.complete else "OK (has sorry)"
            return f"✓ {tag} ({self.elapsed:.1f}s, env={self.env})"
        return f"✗ FAILED ({self.elapsed:.1f}s, {len(self.errors)} errors)"


def _parse_raw(raw: dict, elapsed: float) -> REPLResult:
    """Parse raw JSON from the REPL into a REPLResult."""
    messages = raw.get("messages", [])
    errors = [m for m in messages if m.get("severity") == "error"]
    warnings = [m for m in messages if m.get("severity") == "warning"]
    infos = [m for m in messages if m.get("severity") == "info"]
    sorries = raw.get("sorries", [])
    tactics = raw.get("tactics", [])

    passed = len(errors) == 0
    complete = passed and not sorries and not any(
        "declaration uses 'sorry'" in w.get("data", "")
        or "failed" in w.get("data", "")
        for w in warnings
    )

    # Preserve every #synthesizeVerilog result. ``verilog`` remains the first
    # block for compatibility with existing one-module callers.
    verilog_modules = []
    for info in infos:
        data = info.get("data", "")
        if "module " in data or "Generated by Sparkle" in data:
            verilog_modules.append(data)
    verilog = verilog_modules[0] if verilog_modules else None

    return REPLResult(
        passed=passed, complete=complete,
        errors=errors, warnings=warnings, infos=infos,
        sorries=sorries, tactics=tactics, env=raw.get("env"),
        verilog=verilog, verilog_modules=verilog_modules,
        elapsed=elapsed, raw=raw,
    )


def _error_result(msg: str, elapsed: float) -> REPLResult:
    """Create an error result when the REPL process fails."""
    return REPLResult(
        passed=False, complete=False,
        errors=[{"severity": "error", "data": msg, "pos": {"line": 0, "column": 0}}],
        warnings=[], infos=[], sorries=[], tactics=[],
        env=None, verilog=None, verilog_modules=[], elapsed=elapsed, raw=None,
    )


class LeanREPL:
    """Manages a single persistent `lake exe repl` process.

    Usage:
        repl = LeanREPL(project_dir="/path/to/sparkle")
        # loads prelude, caches env
        result = repl.check_code("def foo := 42")
        print(result.passed, result.error_text)
        repl.close()
    """

    def __init__(
        self,
        project_dir: str | Path = ".",
        timeout: int = DEFAULT_TIMEOUT,
        prelude: str = SPARKLE_PRELUDE,
    ):
        self.project_dir = Path(project_dir).resolve()
        self.timeout = timeout
        self.prelude = prelude
        self._proc: subprocess.Popen | None = None
        self._lock = threading.Lock()  # protects _proc access
        self._prelude_env: int | None = None
        # Public env handles never alias snapshots from a retired process.
        self._env_ids: dict[int, int] = {}
        self._wire_env_ids: dict[int, int] = {}
        self._next_env = 0
        self._start()
        self._load_prelude()

    def _start(self) -> None:
        """Start (or restart) the REPL subprocess."""
        self._close_proc()
        self._proc = subprocess.Popen(
            [LAKE_PATH, "exe", "repl"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=0,
            start_new_session=True,
            cwd=str(self.project_dir),
        )
        try:
            for stream in (self._proc.stdin, self._proc.stdout, self._proc.stderr):
                os.set_blocking(stream.fileno(), False)
        except Exception:
            self._close_proc()
            raise

    def _close_proc(self) -> None:
        """Retire the session, including any child launched by lake."""
        proc, self._proc = self._proc, None
        self._prelude_env = None
        self._env_ids.clear()
        self._wire_env_ids.clear()
        if proc is None:
            return
        try:
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                pass
        finally:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            proc.wait()
            for stream in (proc.stdin, proc.stdout, proc.stderr):
                stream.close()

    def _load_prelude(self) -> None:
        """Load the Sparkle prelude and cache its env."""
        result = self._send_raw(self.prelude, env=None)
        if result.passed and result.env is not None:
            self._prelude_env = result.env
        else:
            self._close_proc()
            raise RuntimeError(
                f"Failed to load Sparkle prelude:\n{result.error_text}"
            )

    def _ensure_ready(self) -> None:
        if (self._proc is None or self._proc.poll() is not None
                or self._prelude_env is None):
            self._start()
            self._load_prelude()

    def _send_raw(self, code: str, env: int | None = None, all_tactics: bool = False) -> REPLResult:
        """Exchange one framed response using deadline-bound POSIX pipe I/O.

        No reader outlives this call. A transport failure retires the process;
        only public entry points may start a new session and reload its prelude.
        """
        proc = self._proc
        if proc is None:
            return _error_result("REPL session is not running", 0)
        if env is not None and env not in self._env_ids:
            return _error_result(
                "REPL environment is stale or unknown; replay definitions from the prelude", 0
            )
        command = {
            "cmd": code,
            "allTactics": all_tactics,
            "ast": False,
            "tactics": all_tactics,
            "premises": False,
        }
        if env is not None:
            command["env"] = self._env_ids[env]

        msg = memoryview((json.dumps(command, ensure_ascii=False) + "\r\n\r\n").encode("utf-8"))
        start = time.monotonic()
        deadline = start + self.timeout
        buf = bytearray()
        stderr_tail = bytearray()

        def fail(reason: str) -> REPLResult:
            elapsed = time.monotonic() - start
            self._close_proc()
            if stderr_tail:
                reason += "\nREPL stderr: " + stderr_tail.decode("utf-8", errors="replace")
            return _error_result(reason + "\nREPL session discarded.", elapsed)

        try:
            with selectors.DefaultSelector() as selector:
                selector.register(proc.stdin, selectors.EVENT_WRITE)
                selector.register(proc.stdout, selectors.EVENT_READ)
                selector.register(proc.stderr, selectors.EVENT_READ)
                while True:
                    remaining = deadline - time.monotonic()
                    if remaining <= 0:
                        state = " (incomplete JSON response)" if buf.strip() else ""
                        return fail(f"REPL I/O timeout after {self.timeout}s{state}")
                    for key, _ in selector.select(remaining):
                        stream = key.fileobj
                        try:
                            if stream is proc.stdin:
                                msg = msg[os.write(key.fd, msg[:65536]):]
                                if not msg:
                                    selector.unregister(stream)
                                continue
                            chunk = os.read(key.fd, 65536)
                        except BlockingIOError:
                            continue
                        if stream is proc.stderr:
                            if chunk:
                                stderr_tail.extend(chunk)
                                del stderr_tail[:-4096]
                            else:
                                selector.unregister(stream)
                            continue
                        if not chunk:
                            return fail("REPL stdout closed before a complete JSON response")
                        buf.extend(chunk)
                        # The community REPL flushes a blank line after each JSON response.
                        framed = buf.replace(b"\r\n", b"\n").lstrip(b"\n")
                        if b"\n\n" not in framed:
                            continue
                        payload, trailing = framed.split(b"\n\n", 1)
                        if trailing.strip():
                            return fail("REPL protocol error: unexpected data after response")
                        raw = json.loads(payload)
                        if not isinstance(raw, dict):
                            return fail("REPL protocol error: response must be a JSON object")
                        result = _parse_raw(raw, time.monotonic() - start)
                        if result.env is not None:
                            wire_env = result.env
                            if type(wire_env) is not int:
                                return fail("REPL protocol error: environment must be an integer")
                            if wire_env not in self._wire_env_ids:
                                handle = self._next_env
                                self._next_env += 1
                                self._wire_env_ids[wire_env] = handle
                                self._env_ids[handle] = wire_env
                            result.env = self._wire_env_ids[wire_env]
                        return result
        except (OSError, ValueError, TypeError, AttributeError) as exc:
            return fail(f"REPL transport/protocol error: {exc}")
        except BaseException:
            self._close_proc()
            raise

    def check_code(self, code: str) -> REPLResult:
        """Verify Lean code incrementally against the cached prelude env.

        This is the main entry point for the agent. The code should NOT include
        `import Sparkle` or `open` statements — those are in the prelude.

        Args:
            code: Lean 4 code to verify (definitions, #synthesizeVerilog, etc.)

        Returns:
            REPLResult with pass/fail, errors, and generated Verilog.
        """
        with self._lock:
            try:
                self._ensure_ready()
            except (OSError, RuntimeError) as exc:
                self._close_proc()
                return _error_result(f"REPL initialization failed: {exc}", 0)
            return self._send_raw(code, env=self._prelude_env)

    def check_code_incremental(self, code: str, env: int | None = None) -> REPLResult:
        """Verify Lean code incrementally with custom env and tactic info.

        Used for interactive proof mode: each call can build on a previous env,
        and returns per-sorry goal states + per-tactic goals.

        Args:
            code: Lean 4 code (defs, theorems, tactics, etc.)
            env: Opaque integer handle from a previous call in this session.
                Invalid after a restart. None = use the current prelude env.

        Returns:
            REPLResult with goal states in `sorries` and tactic trace in `tactics`.
        """
        with self._lock:
            try:
                self._ensure_ready()
            except (OSError, RuntimeError) as exc:
                self._close_proc()
                return _error_result(f"REPL initialization failed: {exc}", 0)
            target_env = env if env is not None else self._prelude_env
            return self._send_raw(code, env=target_env, all_tactics=True)

    def check_file(self, filepath: str | Path) -> REPLResult:
        """Verify a .lean file, stripping prelude imports.

        Reads the file, removes import/open lines that are already in the
        prelude, and sends the remaining code to the REPL.
        """
        content = Path(filepath).read_text()
        # Strip lines that are already in the prelude
        stripped_lines = []
        for line in content.splitlines():
            stripped = line.strip()
            if stripped in ("import Sparkle", "import Sparkle.Compiler.Elab",
                            "open Sparkle.Core.Domain", "open Sparkle.Core.Signal",
                            ""):
                continue
            stripped_lines.append(line)
        code = "\n".join(stripped_lines)
        return self.check_code(code)

    def restart(self) -> None:
        """Restart the REPL process and reload prelude."""
        with self._lock:
            self._start()
            self._load_prelude()

    def close(self) -> None:
        """Shutdown the REPL process."""
        with self._lock:
            self._close_proc()

    @property
    def prelude_env(self) -> int | None:
        """The cached prelude environment ID."""
        return self._prelude_env

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()


class LeanREPLPool:
    """Pool of REPL instances for concurrent workers.

    Each worker gets its own REPL subprocess to avoid contention.
    """

    def __init__(
        self,
        size: int,
        project_dir: str | Path = ".",
        timeout: int = DEFAULT_TIMEOUT,
        prelude_timeout: int = 300,
    ):
        self.project_dir = Path(project_dir).resolve()
        self.timeout = timeout
        self.prelude_timeout = prelude_timeout
        self._pool: list[LeanREPL] = []
        self._available: list[LeanREPL] = []
        self._lock = threading.Lock()
        self._size = size
        # Eagerly init all instances sequentially to avoid concurrent
        # prelude loading which causes timeouts under resource contention.
        for i in range(size):
            repl = LeanREPL(
                project_dir=self.project_dir,
                timeout=self.prelude_timeout,
            )
            # Reset timeout to normal after prelude is loaded
            repl.timeout = self.timeout
            self._pool.append(repl)
            self._available.append(repl)

    def acquire(self) -> LeanREPL:
        """Get a REPL instance (blocks if none available)."""
        while True:
            with self._lock:
                if self._available:
                    return self._available.pop()
            time.sleep(0.1)

    def release(self, repl: LeanREPL) -> None:
        """Return a REPL instance to the pool."""
        with self._lock:
            self._available.append(repl)

    def close_all(self) -> None:
        """Shutdown all REPL instances."""
        with self._lock:
            for repl in self._pool:
                repl.close()
            self._pool.clear()
            self._available.clear()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close_all()
